set(_CATKIN_CURRENT_PACKAGE "multisim_gazebo")
set(multisim_gazebo_VERSION "0.0.0")
set(multisim_gazebo_MAINTAINER "user <user@example.com>")
set(multisim_gazebo_PACKAGE_FORMAT "2")
set(multisim_gazebo_BUILD_DEPENDS "roscpp")
set(multisim_gazebo_BUILD_EXPORT_DEPENDS )
set(multisim_gazebo_BUILDTOOL_DEPENDS "catkin")
set(multisim_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(multisim_gazebo_EXEC_DEPENDS "roscpp")
set(multisim_gazebo_RUN_DEPENDS "roscpp")
set(multisim_gazebo_TEST_DEPENDS )
set(multisim_gazebo_DOC_DEPENDS )
set(multisim_gazebo_URL_WEBSITE "")
set(multisim_gazebo_URL_BUGTRACKER "")
set(multisim_gazebo_URL_REPOSITORY "")
set(multisim_gazebo_DEPRECATED "")