set(_CATKIN_CURRENT_PACKAGE "lowres_map_lite")
set(lowres_map_lite_VERSION "0.0.0")
set(lowres_map_lite_MAINTAINER "CharlieDog <charlie_dog@163.com>")
set(lowres_map_lite_PACKAGE_FORMAT "2")
set(lowres_map_lite_BUILD_DEPENDS "roscpp" "tf" "visualization_msgs" "pcl_conversions" "pcl_ros" "sensor_msgs" "geometry_msgs" "block_map_lite" "glog_catkin" "gflags_catkin")
set(lowres_map_lite_BUILD_EXPORT_DEPENDS "roscpp" "tf" "visualization_msgs" "pcl_conversions" "pcl_ros" "sensor_msgs" "geometry_msgs" "block_map_lite" "glog_catkin" "gflags_catkin")
set(lowres_map_lite_BUILDTOOL_DEPENDS "catkin" "catkin_simple")
set(lowres_map_lite_BUILDTOOL_EXPORT_DEPENDS )
set(lowres_map_lite_EXEC_DEPENDS "roscpp" "tf" "visualization_msgs" "pcl_conversions" "pcl_ros" "sensor_msgs" "geometry_msgs" "block_map_lite" "glog_catkin" "gflags_catkin")
set(lowres_map_lite_RUN_DEPENDS "roscpp" "tf" "visualization_msgs" "pcl_conversions" "pcl_ros" "sensor_msgs" "geometry_msgs" "block_map_lite" "glog_catkin" "gflags_catkin")
set(lowres_map_lite_TEST_DEPENDS )
set(lowres_map_lite_DOC_DEPENDS )
set(lowres_map_lite_URL_WEBSITE "")
set(lowres_map_lite_URL_BUGTRACKER "")
set(lowres_map_lite_URL_REPOSITORY "")
set(lowres_map_lite_DEPRECATED "")