// Generated by gencpp from file exp_comm_msgs/DtgBagC.msg
// DO NOT EDIT!


#ifndef EXP_COMM_MSGS_MESSAGE_DTGBAGC_H
#define EXP_COMM_MSGS_MESSAGE_DTGBAGC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <swarm_exp_msgs/DtgFFEdge.h>
#include <swarm_exp_msgs/DtgHFEdge.h>
#include <swarm_exp_msgs/DtgHHEdge.h>
#include <swarm_exp_msgs/DtgHNode.h>
#include <swarm_exp_msgs/DtgFNode.h>

namespace exp_comm_msgs
{
template <class ContainerAllocator>
struct DtgBagC_
{
  typedef DtgBagC_<ContainerAllocator> Type;

  DtgBagC_()
    : pub_t(0.0)
    , id(0)
    , from_uav(0)
    , FFedges()
    , HFedges()
    , HHedges()
    , Hnodes()
    , Fnodes()  {
    }
  DtgBagC_(const ContainerAllocator& _alloc)
    : pub_t(0.0)
    , id(0)
    , from_uav(0)
    , FFedges(_alloc)
    , HFedges(_alloc)
    , HHedges(_alloc)
    , Hnodes(_alloc)
    , Fnodes(_alloc)  {
  (void)_alloc;
    }



   typedef double _pub_t_type;
  _pub_t_type pub_t;

   typedef uint32_t _id_type;
  _id_type id;

   typedef uint8_t _from_uav_type;
  _from_uav_type from_uav;

   typedef std::vector< ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator> >> _FFedges_type;
  _FFedges_type FFedges;

   typedef std::vector< ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator> >> _HFedges_type;
  _HFedges_type HFedges;

   typedef std::vector< ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator> >> _HHedges_type;
  _HHedges_type HHedges;

   typedef std::vector< ::swarm_exp_msgs::DtgHNode_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::swarm_exp_msgs::DtgHNode_<ContainerAllocator> >> _Hnodes_type;
  _Hnodes_type Hnodes;

   typedef std::vector< ::swarm_exp_msgs::DtgFNode_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::swarm_exp_msgs::DtgFNode_<ContainerAllocator> >> _Fnodes_type;
  _Fnodes_type Fnodes;





  typedef boost::shared_ptr< ::exp_comm_msgs::DtgBagC_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exp_comm_msgs::DtgBagC_<ContainerAllocator> const> ConstPtr;

}; // struct DtgBagC_

typedef ::exp_comm_msgs::DtgBagC_<std::allocator<void> > DtgBagC;

typedef boost::shared_ptr< ::exp_comm_msgs::DtgBagC > DtgBagCPtr;
typedef boost::shared_ptr< ::exp_comm_msgs::DtgBagC const> DtgBagCConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exp_comm_msgs::DtgBagC_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exp_comm_msgs::DtgBagC_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exp_comm_msgs::DtgBagC_<ContainerAllocator1> & lhs, const ::exp_comm_msgs::DtgBagC_<ContainerAllocator2> & rhs)
{
  return lhs.pub_t == rhs.pub_t &&
    lhs.id == rhs.id &&
    lhs.from_uav == rhs.from_uav &&
    lhs.FFedges == rhs.FFedges &&
    lhs.HFedges == rhs.HFedges &&
    lhs.HHedges == rhs.HHedges &&
    lhs.Hnodes == rhs.Hnodes &&
    lhs.Fnodes == rhs.Fnodes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exp_comm_msgs::DtgBagC_<ContainerAllocator1> & lhs, const ::exp_comm_msgs::DtgBagC_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exp_comm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::exp_comm_msgs::DtgBagC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exp_comm_msgs::DtgBagC_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exp_comm_msgs::DtgBagC_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exp_comm_msgs::DtgBagC_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp_comm_msgs::DtgBagC_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp_comm_msgs::DtgBagC_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exp_comm_msgs::DtgBagC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff41106c2b664f3ededcb2a753d90eeb";
  }

  static const char* value(const ::exp_comm_msgs::DtgBagC_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff41106c2b664f3eULL;
  static const uint64_t static_value2 = 0xdedcb2a753d90eebULL;
};

template<class ContainerAllocator>
struct DataType< ::exp_comm_msgs::DtgBagC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exp_comm_msgs/DtgBagC";
  }

  static const char* value(const ::exp_comm_msgs::DtgBagC_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exp_comm_msgs::DtgBagC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 pub_t\n"
"uint32 id\n"
"uint8 from_uav\n"
"swarm_exp_msgs/DtgFFEdge[] FFedges\n"
"swarm_exp_msgs/DtgHFEdge[] HFedges\n"
"swarm_exp_msgs/DtgHHEdge[] HHedges\n"
"swarm_exp_msgs/DtgHNode[] Hnodes\n"
"swarm_exp_msgs/DtgFNode[] Fnodes \n"
"================================================================================\n"
"MSG: swarm_exp_msgs/DtgFFEdge\n"
"uint16 head_f_id\n"
"uint16 tail_f_id\n"
"uint32[] points_idx #low res map\n"
"\n"
"uint8 head_v_id #viewpoint id of head fn\n"
"uint8 tail_v_id #viewpoint id of tail fn\n"
"uint8 ffe_id    #who creates\n"
"\n"
"================================================================================\n"
"MSG: swarm_exp_msgs/DtgHFEdge\n"
"uint32[] points_idx #low res map\n"
"float64 pub_t\n"
"uint16 f_id\n"
"uint32 h_id\n"
"uint8 vp_id\n"
"#uint8 hfe_id        #who creates\n"
"\n"
"================================================================================\n"
"MSG: swarm_exp_msgs/DtgHHEdge\n"
"#uint8 hhe_id        #who creates\n"
"#bool erase \n"
"float64 pub_t\n"
"uint32[] points_idx #low res map\n"
"uint32 head_h_id\n"
"uint32 tail_h_id\n"
"================================================================================\n"
"MSG: swarm_exp_msgs/DtgHNode\n"
"uint32 h_id\n"
"uint32 pos_idx #low res map\n"
"================================================================================\n"
"MSG: swarm_exp_msgs/DtgFNode\n"
"uint16 f_id\n"
"bool alive\n"
"uint8[] vp_flags #(alive dead)(alive dead)(alive dead)(alive dead)\n"
"uint8 need_help # ask other uav for edge\n"
;
  }

  static const char* value(const ::exp_comm_msgs::DtgBagC_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exp_comm_msgs::DtgBagC_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pub_t);
      stream.next(m.id);
      stream.next(m.from_uav);
      stream.next(m.FFedges);
      stream.next(m.HFedges);
      stream.next(m.HHedges);
      stream.next(m.Hnodes);
      stream.next(m.Fnodes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DtgBagC_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exp_comm_msgs::DtgBagC_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exp_comm_msgs::DtgBagC_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "pub_t: ";
    Printer<double>::stream(s, indent + "  ", v.pub_t);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "from_uav: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.from_uav);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "FFedges: ";
    if (v.FFedges.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.FFedges.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.FFedges[i]);
    }
    if (v.FFedges.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "HFedges: ";
    if (v.HFedges.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.HFedges.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.HFedges[i]);
    }
    if (v.HFedges.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "HHedges: ";
    if (v.HHedges.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.HHedges.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.HHedges[i]);
    }
    if (v.HHedges.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Hnodes: ";
    if (v.Hnodes.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.Hnodes.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::swarm_exp_msgs::DtgHNode_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.Hnodes[i]);
    }
    if (v.Hnodes.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Fnodes: ";
    if (v.Fnodes.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.Fnodes.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::swarm_exp_msgs::DtgFNode_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.Fnodes[i]);
    }
    if (v.Fnodes.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXP_COMM_MSGS_MESSAGE_DTGBAGC_H
