// Generated by gencpp from file exp_comm_msgs/DtgBagAnswer.msg
// DO NOT EDIT!


#ifndef EXP_COMM_MSGS_MESSAGE_DTGBAGANSWER_H
#define EXP_COMM_MSGS_MESSAGE_DTGBAGANSWER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exp_comm_msgs
{
template <class ContainerAllocator>
struct DtgBagAnswer_
{
  typedef DtgBagAnswer_<ContainerAllocator> Type;

  DtgBagAnswer_()
    : id(0)
    , to_uav(0)
    , bag_id(0)  {
    }
  DtgBagAnswer_(const ContainerAllocator& _alloc)
    : id(0)
    , to_uav(0)
    , bag_id(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef uint8_t _to_uav_type;
  _to_uav_type to_uav;

   typedef uint32_t _bag_id_type;
  _bag_id_type bag_id;





  typedef boost::shared_ptr< ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator> const> ConstPtr;

}; // struct DtgBagAnswer_

typedef ::exp_comm_msgs::DtgBagAnswer_<std::allocator<void> > DtgBagAnswer;

typedef boost::shared_ptr< ::exp_comm_msgs::DtgBagAnswer > DtgBagAnswerPtr;
typedef boost::shared_ptr< ::exp_comm_msgs::DtgBagAnswer const> DtgBagAnswerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator1> & lhs, const ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.to_uav == rhs.to_uav &&
    lhs.bag_id == rhs.bag_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator1> & lhs, const ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exp_comm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "38ef4e8bfd92de589cce314b18d25dfb";
  }

  static const char* value(const ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x38ef4e8bfd92de58ULL;
  static const uint64_t static_value2 = 0x9cce314b18d25dfbULL;
};

template<class ContainerAllocator>
struct DataType< ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exp_comm_msgs/DtgBagAnswer";
  }

  static const char* value(const ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"uint8 to_uav\n"
"uint32 bag_id\n"
;
  }

  static const char* value(const ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.to_uav);
      stream.next(m.bag_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DtgBagAnswer_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exp_comm_msgs::DtgBagAnswer_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "to_uav: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.to_uav);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bag_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.bag_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXP_COMM_MSGS_MESSAGE_DTGBAGANSWER_H
