// Generated by gencpp from file exp_comm_msgs/IdPoseC.msg
// DO NOT EDIT!


#ifndef EXP_COMM_MSGS_MESSAGE_IDPOSEC_H
#define EXP_COMM_MSGS_MESSAGE_IDPOSEC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace exp_comm_msgs
{
template <class ContainerAllocator>
struct IdPoseC_
{
  typedef IdPoseC_<ContainerAllocator> Type;

  IdPoseC_()
    : id(0)
    , pub_t(0.0)
    , pose()  {
    }
  IdPoseC_(const ContainerAllocator& _alloc)
    : id(0)
    , pub_t(0.0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef double _pub_t_type;
  _pub_t_type pub_t;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::exp_comm_msgs::IdPoseC_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exp_comm_msgs::IdPoseC_<ContainerAllocator> const> ConstPtr;

}; // struct IdPoseC_

typedef ::exp_comm_msgs::IdPoseC_<std::allocator<void> > IdPoseC;

typedef boost::shared_ptr< ::exp_comm_msgs::IdPoseC > IdPoseCPtr;
typedef boost::shared_ptr< ::exp_comm_msgs::IdPoseC const> IdPoseCConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exp_comm_msgs::IdPoseC_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exp_comm_msgs::IdPoseC_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exp_comm_msgs::IdPoseC_<ContainerAllocator1> & lhs, const ::exp_comm_msgs::IdPoseC_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.pub_t == rhs.pub_t &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exp_comm_msgs::IdPoseC_<ContainerAllocator1> & lhs, const ::exp_comm_msgs::IdPoseC_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exp_comm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::exp_comm_msgs::IdPoseC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exp_comm_msgs::IdPoseC_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exp_comm_msgs::IdPoseC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exp_comm_msgs::IdPoseC_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp_comm_msgs::IdPoseC_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp_comm_msgs::IdPoseC_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exp_comm_msgs::IdPoseC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7bae89dc6e8db6dcfb244807a95d689";
  }

  static const char* value(const ::exp_comm_msgs::IdPoseC_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7bae89dc6e8db6dULL;
  static const uint64_t static_value2 = 0xcfb244807a95d689ULL;
};

template<class ContainerAllocator>
struct DataType< ::exp_comm_msgs::IdPoseC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exp_comm_msgs/IdPoseC";
  }

  static const char* value(const ::exp_comm_msgs::IdPoseC_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exp_comm_msgs::IdPoseC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"float64 pub_t\n"
"geometry_msgs/Pose pose\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::exp_comm_msgs::IdPoseC_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exp_comm_msgs::IdPoseC_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.pub_t);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IdPoseC_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exp_comm_msgs::IdPoseC_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exp_comm_msgs::IdPoseC_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pub_t: ";
    Printer<double>::stream(s, indent + "  ", v.pub_t);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXP_COMM_MSGS_MESSAGE_IDPOSEC_H
