// Generated by gencpp from file exp_comm_msgs/MapC.msg
// DO NOT EDIT!


#ifndef EXP_COMM_MSGS_MESSAGE_MAPC_H
#define EXP_COMM_MSGS_MESSAGE_MAPC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exp_comm_msgs
{
template <class ContainerAllocator>
struct MapC_
{
  typedef MapC_<ContainerAllocator> Type;

  MapC_()
    : f_id(0)
    , block_id(0)
    , block_state(0)
    , flags()  {
    }
  MapC_(const ContainerAllocator& _alloc)
    : f_id(0)
    , block_id(0)
    , block_state(0)
    , flags(_alloc)  {
  (void)_alloc;
    }



   typedef uint16_t _f_id_type;
  _f_id_type f_id;

   typedef uint8_t _block_id_type;
  _block_id_type block_id;

   typedef uint8_t _block_state_type;
  _block_state_type block_state;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _flags_type;
  _flags_type flags;





  typedef boost::shared_ptr< ::exp_comm_msgs::MapC_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exp_comm_msgs::MapC_<ContainerAllocator> const> ConstPtr;

}; // struct MapC_

typedef ::exp_comm_msgs::MapC_<std::allocator<void> > MapC;

typedef boost::shared_ptr< ::exp_comm_msgs::MapC > MapCPtr;
typedef boost::shared_ptr< ::exp_comm_msgs::MapC const> MapCConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exp_comm_msgs::MapC_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exp_comm_msgs::MapC_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exp_comm_msgs::MapC_<ContainerAllocator1> & lhs, const ::exp_comm_msgs::MapC_<ContainerAllocator2> & rhs)
{
  return lhs.f_id == rhs.f_id &&
    lhs.block_id == rhs.block_id &&
    lhs.block_state == rhs.block_state &&
    lhs.flags == rhs.flags;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exp_comm_msgs::MapC_<ContainerAllocator1> & lhs, const ::exp_comm_msgs::MapC_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exp_comm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::exp_comm_msgs::MapC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exp_comm_msgs::MapC_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exp_comm_msgs::MapC_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exp_comm_msgs::MapC_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp_comm_msgs::MapC_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp_comm_msgs::MapC_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exp_comm_msgs::MapC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f846807ed51661abe48fa122b2e37650";
  }

  static const char* value(const ::exp_comm_msgs::MapC_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf846807ed51661abULL;
  static const uint64_t static_value2 = 0xe48fa122b2e37650ULL;
};

template<class ContainerAllocator>
struct DataType< ::exp_comm_msgs::MapC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exp_comm_msgs/MapC";
  }

  static const char* value(const ::exp_comm_msgs::MapC_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exp_comm_msgs::MapC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 f_id\n"
"uint8 block_id #1-8\n"
"uint8 block_state #0: unknown 1:occ 2:free 3:mix\n"
"uint8[] flags #00 00 00 00  (free occ)(free occ)(free occ)(free occ)\n"
;
  }

  static const char* value(const ::exp_comm_msgs::MapC_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exp_comm_msgs::MapC_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.f_id);
      stream.next(m.block_id);
      stream.next(m.block_state);
      stream.next(m.flags);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapC_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exp_comm_msgs::MapC_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exp_comm_msgs::MapC_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "f_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.f_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "block_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.block_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "block_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.block_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flags: ";
    if (v.flags.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.flags.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.flags[i]);
    }
    if (v.flags.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXP_COMM_MSGS_MESSAGE_MAPC_H
