// Generated by gencpp from file exp_comm_msgs/MapReqC.msg
// DO NOT EDIT!


#ifndef EXP_COMM_MSGS_MESSAGE_MAPREQC_H
#define EXP_COMM_MSGS_MESSAGE_MAPREQC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exp_comm_msgs
{
template <class ContainerAllocator>
struct MapReqC_
{
  typedef MapReqC_<ContainerAllocator> Type;

  MapReqC_()
    : f_id()
    , block_id()
    , flag(0)  {
    }
  MapReqC_(const ContainerAllocator& _alloc)
    : f_id(_alloc)
    , block_id(_alloc)
    , flag(0)  {
  (void)_alloc;
    }



   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _f_id_type;
  _f_id_type f_id;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _block_id_type;
  _block_id_type block_id;

   typedef uint8_t _flag_type;
  _flag_type flag;





  typedef boost::shared_ptr< ::exp_comm_msgs::MapReqC_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exp_comm_msgs::MapReqC_<ContainerAllocator> const> ConstPtr;

}; // struct MapReqC_

typedef ::exp_comm_msgs::MapReqC_<std::allocator<void> > MapReqC;

typedef boost::shared_ptr< ::exp_comm_msgs::MapReqC > MapReqCPtr;
typedef boost::shared_ptr< ::exp_comm_msgs::MapReqC const> MapReqCConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exp_comm_msgs::MapReqC_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exp_comm_msgs::MapReqC_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exp_comm_msgs::MapReqC_<ContainerAllocator1> & lhs, const ::exp_comm_msgs::MapReqC_<ContainerAllocator2> & rhs)
{
  return lhs.f_id == rhs.f_id &&
    lhs.block_id == rhs.block_id &&
    lhs.flag == rhs.flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exp_comm_msgs::MapReqC_<ContainerAllocator1> & lhs, const ::exp_comm_msgs::MapReqC_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exp_comm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::exp_comm_msgs::MapReqC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exp_comm_msgs::MapReqC_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exp_comm_msgs::MapReqC_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exp_comm_msgs::MapReqC_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp_comm_msgs::MapReqC_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp_comm_msgs::MapReqC_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exp_comm_msgs::MapReqC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71af631c49d7e61ef9c70b1b03b18a05";
  }

  static const char* value(const ::exp_comm_msgs::MapReqC_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71af631c49d7e61eULL;
  static const uint64_t static_value2 = 0xf9c70b1b03b18a05ULL;
};

template<class ContainerAllocator>
struct DataType< ::exp_comm_msgs::MapReqC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exp_comm_msgs/MapReqC";
  }

  static const char* value(const ::exp_comm_msgs::MapReqC_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exp_comm_msgs::MapReqC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16[] f_id\n"
"uint8[] block_id\n"
"uint8 flag\n"
;
  }

  static const char* value(const ::exp_comm_msgs::MapReqC_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exp_comm_msgs::MapReqC_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.f_id);
      stream.next(m.block_id);
      stream.next(m.flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapReqC_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exp_comm_msgs::MapReqC_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exp_comm_msgs::MapReqC_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "f_id: ";
    if (v.f_id.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.f_id.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint16_t>::stream(s, true ? std::string() : indent + "    ", v.f_id[i]);
    }
    if (v.f_id.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "block_id: ";
    if (v.block_id.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.block_id.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.block_id[i]);
    }
    if (v.block_id.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXP_COMM_MSGS_MESSAGE_MAPREQC_H
