// Generated by gencpp from file exp_comm_msgs/SwarmTrajC.msg
// DO NOT EDIT!


#ifndef EXP_COMM_MSGS_MESSAGE_SWARMTRAJC_H
#define EXP_COMM_MSGS_MESSAGE_SWARMTRAJC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace exp_comm_msgs
{
template <class ContainerAllocator>
struct SwarmTrajC_
{
  typedef SwarmTrajC_<ContainerAllocator> Type;

  SwarmTrajC_()
    : pub_t(0.0)
    , id(0)
    , start_t(0.0)
    , order_p(0)
    , t_p()
    , coef_p()  {
    }
  SwarmTrajC_(const ContainerAllocator& _alloc)
    : pub_t(0.0)
    , id(0)
    , start_t(0.0)
    , order_p(0)
    , t_p(_alloc)
    , coef_p(_alloc)  {
  (void)_alloc;
    }



   typedef double _pub_t_type;
  _pub_t_type pub_t;

   typedef uint8_t _id_type;
  _id_type id;

   typedef double _start_t_type;
  _start_t_type start_t;

   typedef int8_t _order_p_type;
  _order_p_type order_p;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _t_p_type;
  _t_p_type t_p;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _coef_p_type;
  _coef_p_type coef_p;





  typedef boost::shared_ptr< ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator> const> ConstPtr;

}; // struct SwarmTrajC_

typedef ::exp_comm_msgs::SwarmTrajC_<std::allocator<void> > SwarmTrajC;

typedef boost::shared_ptr< ::exp_comm_msgs::SwarmTrajC > SwarmTrajCPtr;
typedef boost::shared_ptr< ::exp_comm_msgs::SwarmTrajC const> SwarmTrajCConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator1> & lhs, const ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator2> & rhs)
{
  return lhs.pub_t == rhs.pub_t &&
    lhs.id == rhs.id &&
    lhs.start_t == rhs.start_t &&
    lhs.order_p == rhs.order_p &&
    lhs.t_p == rhs.t_p &&
    lhs.coef_p == rhs.coef_p;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator1> & lhs, const ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exp_comm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b412e83c14c239c5f9f2ca748f0bead0";
  }

  static const char* value(const ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb412e83c14c239c5ULL;
  static const uint64_t static_value2 = 0xf9f2ca748f0bead0ULL;
};

template<class ContainerAllocator>
struct DataType< ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exp_comm_msgs/SwarmTrajC";
  }

  static const char* value(const ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 pub_t\n"
"\n"
"uint8 id\n"
"\n"
"float64 start_t\n"
"int8 order_p\n"
"float32[] t_p\n"
"geometry_msgs/Point[] coef_p\n"
"\n"
"# int8 order_yaw\n"
"# float32[] t_yaw\n"
"# float32[] coef_yaw\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pub_t);
      stream.next(m.id);
      stream.next(m.start_t);
      stream.next(m.order_p);
      stream.next(m.t_p);
      stream.next(m.coef_p);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SwarmTrajC_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exp_comm_msgs::SwarmTrajC_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "pub_t: ";
    Printer<double>::stream(s, indent + "  ", v.pub_t);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "start_t: ";
    Printer<double>::stream(s, indent + "  ", v.start_t);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "order_p: ";
    Printer<int8_t>::stream(s, indent + "  ", v.order_p);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "t_p: ";
    if (v.t_p.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.t_p.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.t_p[i]);
    }
    if (v.t_p.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "coef_p: ";
    if (v.coef_p.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.coef_p.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.coef_p[i]);
    }
    if (v.coef_p.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXP_COMM_MSGS_MESSAGE_SWARMTRAJC_H
