// Generated by gencpp from file exp_comm_msgs/SwarmJobC.msg
// DO NOT EDIT!


#ifndef EXP_COMM_MSGS_MESSAGE_SWARMJOBC_H
#define EXP_COMM_MSGS_MESSAGE_SWARMJOBC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exp_comm_msgs
{
template <class ContainerAllocator>
struct SwarmJobC_
{
  typedef SwarmJobC_<ContainerAllocator> Type;

  SwarmJobC_()
    : pub_t(0.0)
    , from_uav(0)
    , JobState(0)
    , target_fn(0)
    , target_hn(0)
    , dist_to_fn(0.0)
    , dist_to_hn(0.0)  {
    }
  SwarmJobC_(const ContainerAllocator& _alloc)
    : pub_t(0.0)
    , from_uav(0)
    , JobState(0)
    , target_fn(0)
    , target_hn(0)
    , dist_to_fn(0.0)
    , dist_to_hn(0.0)  {
  (void)_alloc;
    }



   typedef double _pub_t_type;
  _pub_t_type pub_t;

   typedef uint8_t _from_uav_type;
  _from_uav_type from_uav;

   typedef uint8_t _JobState_type;
  _JobState_type JobState;

   typedef int32_t _target_fn_type;
  _target_fn_type target_fn;

   typedef int32_t _target_hn_type;
  _target_hn_type target_hn;

   typedef float _dist_to_fn_type;
  _dist_to_fn_type dist_to_fn;

   typedef float _dist_to_hn_type;
  _dist_to_hn_type dist_to_hn;





  typedef boost::shared_ptr< ::exp_comm_msgs::SwarmJobC_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exp_comm_msgs::SwarmJobC_<ContainerAllocator> const> ConstPtr;

}; // struct SwarmJobC_

typedef ::exp_comm_msgs::SwarmJobC_<std::allocator<void> > SwarmJobC;

typedef boost::shared_ptr< ::exp_comm_msgs::SwarmJobC > SwarmJobCPtr;
typedef boost::shared_ptr< ::exp_comm_msgs::SwarmJobC const> SwarmJobCConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exp_comm_msgs::SwarmJobC_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exp_comm_msgs::SwarmJobC_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exp_comm_msgs::SwarmJobC_<ContainerAllocator1> & lhs, const ::exp_comm_msgs::SwarmJobC_<ContainerAllocator2> & rhs)
{
  return lhs.pub_t == rhs.pub_t &&
    lhs.from_uav == rhs.from_uav &&
    lhs.JobState == rhs.JobState &&
    lhs.target_fn == rhs.target_fn &&
    lhs.target_hn == rhs.target_hn &&
    lhs.dist_to_fn == rhs.dist_to_fn &&
    lhs.dist_to_hn == rhs.dist_to_hn;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exp_comm_msgs::SwarmJobC_<ContainerAllocator1> & lhs, const ::exp_comm_msgs::SwarmJobC_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exp_comm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::exp_comm_msgs::SwarmJobC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exp_comm_msgs::SwarmJobC_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exp_comm_msgs::SwarmJobC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exp_comm_msgs::SwarmJobC_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp_comm_msgs::SwarmJobC_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp_comm_msgs::SwarmJobC_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exp_comm_msgs::SwarmJobC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e25c09eda529caf2748eb82a8886575b";
  }

  static const char* value(const ::exp_comm_msgs::SwarmJobC_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe25c09eda529caf2ULL;
  static const uint64_t static_value2 = 0x748eb82a8886575bULL;
};

template<class ContainerAllocator>
struct DataType< ::exp_comm_msgs::SwarmJobC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exp_comm_msgs/SwarmJobC";
  }

  static const char* value(const ::exp_comm_msgs::SwarmJobC_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exp_comm_msgs::SwarmJobC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 pub_t\n"
"uint8 from_uav\n"
"uint8 JobState #0000 0(no job = 0/ new job = 1)(finish = 1)(local = 0/ global = 1)\n"
"int32  target_fn\n"
"int32 target_hn\n"
"float32 dist_to_fn\n"
"float32 dist_to_hn\n"
"\n"
"\n"
;
  }

  static const char* value(const ::exp_comm_msgs::SwarmJobC_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exp_comm_msgs::SwarmJobC_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pub_t);
      stream.next(m.from_uav);
      stream.next(m.JobState);
      stream.next(m.target_fn);
      stream.next(m.target_hn);
      stream.next(m.dist_to_fn);
      stream.next(m.dist_to_hn);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SwarmJobC_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exp_comm_msgs::SwarmJobC_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exp_comm_msgs::SwarmJobC_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "pub_t: ";
    Printer<double>::stream(s, indent + "  ", v.pub_t);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "from_uav: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.from_uav);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "JobState: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.JobState);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_fn: ";
    Printer<int32_t>::stream(s, indent + "  ", v.target_fn);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_hn: ";
    Printer<int32_t>::stream(s, indent + "  ", v.target_hn);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dist_to_fn: ";
    Printer<float>::stream(s, indent + "  ", v.dist_to_fn);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dist_to_hn: ";
    Printer<float>::stream(s, indent + "  ", v.dist_to_hn);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXP_COMM_MSGS_MESSAGE_SWARMJOBC_H
