// Generated by gencpp from file exp_comm_msgs/SwarmStateC.msg
// DO NOT EDIT!


#ifndef EXP_COMM_MSGS_MESSAGE_SWARMSTATEC_H
#define EXP_COMM_MSGS_MESSAGE_SWARMSTATEC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exp_comm_msgs
{
template <class ContainerAllocator>
struct SwarmStateC_
{
  typedef SwarmStateC_<ContainerAllocator> Type;

  SwarmStateC_()
    : pub_t(0.0)
    , from_uav(0)
    , flags(0)
    , local_fn()
    , dist_to_local_fn()
    , connect_fn()
    , dist_to_connect_fn()
    , connect_hn()
    , hn_pos_idx()
    , dist_to_connect_hn()  {
    }
  SwarmStateC_(const ContainerAllocator& _alloc)
    : pub_t(0.0)
    , from_uav(0)
    , flags(0)
    , local_fn(_alloc)
    , dist_to_local_fn(_alloc)
    , connect_fn(_alloc)
    , dist_to_connect_fn(_alloc)
    , connect_hn(_alloc)
    , hn_pos_idx(_alloc)
    , dist_to_connect_hn(_alloc)  {
  (void)_alloc;
    }



   typedef double _pub_t_type;
  _pub_t_type pub_t;

   typedef uint8_t _from_uav_type;
  _from_uav_type from_uav;

   typedef uint8_t _flags_type;
  _flags_type flags;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _local_fn_type;
  _local_fn_type local_fn;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _dist_to_local_fn_type;
  _dist_to_local_fn_type dist_to_local_fn;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _connect_fn_type;
  _connect_fn_type connect_fn;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _dist_to_connect_fn_type;
  _dist_to_connect_fn_type dist_to_connect_fn;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _connect_hn_type;
  _connect_hn_type connect_hn;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _hn_pos_idx_type;
  _hn_pos_idx_type hn_pos_idx;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _dist_to_connect_hn_type;
  _dist_to_connect_hn_type dist_to_connect_hn;





  typedef boost::shared_ptr< ::exp_comm_msgs::SwarmStateC_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exp_comm_msgs::SwarmStateC_<ContainerAllocator> const> ConstPtr;

}; // struct SwarmStateC_

typedef ::exp_comm_msgs::SwarmStateC_<std::allocator<void> > SwarmStateC;

typedef boost::shared_ptr< ::exp_comm_msgs::SwarmStateC > SwarmStateCPtr;
typedef boost::shared_ptr< ::exp_comm_msgs::SwarmStateC const> SwarmStateCConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exp_comm_msgs::SwarmStateC_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exp_comm_msgs::SwarmStateC_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exp_comm_msgs::SwarmStateC_<ContainerAllocator1> & lhs, const ::exp_comm_msgs::SwarmStateC_<ContainerAllocator2> & rhs)
{
  return lhs.pub_t == rhs.pub_t &&
    lhs.from_uav == rhs.from_uav &&
    lhs.flags == rhs.flags &&
    lhs.local_fn == rhs.local_fn &&
    lhs.dist_to_local_fn == rhs.dist_to_local_fn &&
    lhs.connect_fn == rhs.connect_fn &&
    lhs.dist_to_connect_fn == rhs.dist_to_connect_fn &&
    lhs.connect_hn == rhs.connect_hn &&
    lhs.hn_pos_idx == rhs.hn_pos_idx &&
    lhs.dist_to_connect_hn == rhs.dist_to_connect_hn;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exp_comm_msgs::SwarmStateC_<ContainerAllocator1> & lhs, const ::exp_comm_msgs::SwarmStateC_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exp_comm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::exp_comm_msgs::SwarmStateC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exp_comm_msgs::SwarmStateC_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exp_comm_msgs::SwarmStateC_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exp_comm_msgs::SwarmStateC_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp_comm_msgs::SwarmStateC_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp_comm_msgs::SwarmStateC_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exp_comm_msgs::SwarmStateC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "11fc39f21c102f3f37a28c1e4132b63e";
  }

  static const char* value(const ::exp_comm_msgs::SwarmStateC_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x11fc39f21c102f3fULL;
  static const uint64_t static_value2 = 0x37a28c1e4132b63eULL;
};

template<class ContainerAllocator>
struct DataType< ::exp_comm_msgs::SwarmStateC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exp_comm_msgs/SwarmStateC";
  }

  static const char* value(const ::exp_comm_msgs::SwarmStateC_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exp_comm_msgs::SwarmStateC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 pub_t\n"
"uint8 from_uav\n"
"uint8 flags #0000 000(quick communication) \n"
"uint16[]  local_fn\n"
"float32[] dist_to_local_fn\n"
"\n"
"uint16[]  connect_fn\n"
"float32[] dist_to_connect_fn\n"
"\n"
"uint32[]  connect_hn\n"
"uint32[]  hn_pos_idx\n"
"float32[] dist_to_connect_hn  \n"
"\n"
;
  }

  static const char* value(const ::exp_comm_msgs::SwarmStateC_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exp_comm_msgs::SwarmStateC_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pub_t);
      stream.next(m.from_uav);
      stream.next(m.flags);
      stream.next(m.local_fn);
      stream.next(m.dist_to_local_fn);
      stream.next(m.connect_fn);
      stream.next(m.dist_to_connect_fn);
      stream.next(m.connect_hn);
      stream.next(m.hn_pos_idx);
      stream.next(m.dist_to_connect_hn);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SwarmStateC_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exp_comm_msgs::SwarmStateC_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exp_comm_msgs::SwarmStateC_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "pub_t: ";
    Printer<double>::stream(s, indent + "  ", v.pub_t);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "from_uav: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.from_uav);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flags: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flags);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "local_fn: ";
    if (v.local_fn.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.local_fn.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint16_t>::stream(s, true ? std::string() : indent + "    ", v.local_fn[i]);
    }
    if (v.local_fn.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dist_to_local_fn: ";
    if (v.dist_to_local_fn.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.dist_to_local_fn.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.dist_to_local_fn[i]);
    }
    if (v.dist_to_local_fn.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "connect_fn: ";
    if (v.connect_fn.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.connect_fn.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint16_t>::stream(s, true ? std::string() : indent + "    ", v.connect_fn[i]);
    }
    if (v.connect_fn.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dist_to_connect_fn: ";
    if (v.dist_to_connect_fn.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.dist_to_connect_fn.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.dist_to_connect_fn[i]);
    }
    if (v.dist_to_connect_fn.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "connect_hn: ";
    if (v.connect_hn.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.connect_hn.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint32_t>::stream(s, true ? std::string() : indent + "    ", v.connect_hn[i]);
    }
    if (v.connect_hn.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hn_pos_idx: ";
    if (v.hn_pos_idx.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.hn_pos_idx.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint32_t>::stream(s, true ? std::string() : indent + "    ", v.hn_pos_idx[i]);
    }
    if (v.hn_pos_idx.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dist_to_connect_hn: ";
    if (v.dist_to_connect_hn.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.dist_to_connect_hn.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.dist_to_connect_hn[i]);
    }
    if (v.dist_to_connect_hn.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXP_COMM_MSGS_MESSAGE_SWARMSTATEC_H
