set(_CATKIN_CURRENT_PACKAGE "swarm_exp_msgs")
set(swarm_exp_msgs_VERSION "0.0.0")
set(swarm_exp_msgs_MAINTAINER "user <user@example.com>")
set(swarm_exp_msgs_PACKAGE_FORMAT "2")
set(swarm_exp_msgs_BUILD_DEPENDS "message_generation")
set(swarm_exp_msgs_BUILD_EXPORT_DEPENDS )
set(swarm_exp_msgs_BUILDTOOL_DEPENDS "catkin")
set(swarm_exp_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(swarm_exp_msgs_EXEC_DEPENDS "message_runtime")
set(swarm_exp_msgs_RUN_DEPENDS "message_runtime")
set(swarm_exp_msgs_TEST_DEPENDS )
set(swarm_exp_msgs_DOC_DEPENDS )
set(swarm_exp_msgs_URL_WEBSITE "")
set(swarm_exp_msgs_URL_BUGTRACKER "")
set(swarm_exp_msgs_URL_REPOSITORY "")
set(swarm_exp_msgs_DEPRECATED "")