set(_CATKIN_CURRENT_PACKAGE "explore_con")
set(explore_con_VERSION "0.0.0")
set(explore_con_MAINTAINER "user <user@example.com>")
set(explore_con_PACKAGE_FORMAT "2")
set(explore_con_BUILD_DEPENDS "roscpp")
set(explore_con_BUILD_EXPORT_DEPENDS )
set(explore_con_BUILDTOOL_DEPENDS "catkin")
set(explore_con_BUILDTOOL_EXPORT_DEPENDS )
set(explore_con_EXEC_DEPENDS "roscpp")
set(explore_con_RUN_DEPENDS "roscpp")
set(explore_con_TEST_DEPENDS )
set(explore_con_DOC_DEPENDS )
set(explore_con_URL_WEBSITE "")
set(explore_con_URL_BUGTRACKER "")
set(explore_con_URL_REPOSITORY "")
set(explore_con_DEPRECATED "")