set(_CATKIN_CURRENT_PACKAGE "exp_comm_msgs")
set(exp_comm_msgs_VERSION "0.0.0")
set(exp_comm_msgs_MAINTAINER "user <user@example.com>")
set(exp_comm_msgs_PACKAGE_FORMAT "2")
set(exp_comm_msgs_BUILD_DEPENDS "message_generation")
set(exp_comm_msgs_BUILD_EXPORT_DEPENDS )
set(exp_comm_msgs_BUILDTOOL_DEPENDS "catkin")
set(exp_comm_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(exp_comm_msgs_EXEC_DEPENDS "message_runtime")
set(exp_comm_msgs_RUN_DEPENDS "message_runtime")
set(exp_comm_msgs_TEST_DEPENDS )
set(exp_comm_msgs_DOC_DEPENDS )
set(exp_comm_msgs_URL_WEBSITE "")
set(exp_comm_msgs_URL_BUGTRACKER "")
set(exp_comm_msgs_URL_REPOSITORY "")
set(exp_comm_msgs_DEPRECATED "")