set(_CATKIN_CURRENT_PACKAGE "pointcloud_render")
set(pointcloud_render_VERSION "0.1.0")
set(pointcloud_render_MAINTAINER "Matia Pizzoli <matia.pizzoli@gmail.com>")
set(pointcloud_render_PACKAGE_FORMAT "2")
set(pointcloud_render_BUILD_DEPENDS "cmake_modules" "roscpp" "roslib" "svo_msgs" "cv_bridge" "image_transport" "vikit_ros" "pcl_ros" "dynamic_reconfigure" "quadrotor_msgs")
set(pointcloud_render_BUILD_EXPORT_DEPENDS "roscpp" "roslib" "svo_msgs" "cv_bridge" "image_transport" "vikit_ros" "pcl_ros" "dynamic_reconfigure" "quadrotor_msgs")
set(pointcloud_render_BUILDTOOL_DEPENDS "catkin")
set(pointcloud_render_BUILDTOOL_EXPORT_DEPENDS )
set(pointcloud_render_EXEC_DEPENDS "roscpp" "roslib" "svo_msgs" "cv_bridge" "image_transport" "vikit_ros" "pcl_ros" "dynamic_reconfigure" "quadrotor_msgs")
set(pointcloud_render_RUN_DEPENDS "roscpp" "roslib" "svo_msgs" "cv_bridge" "image_transport" "vikit_ros" "pcl_ros" "dynamic_reconfigure" "quadrotor_msgs")
set(pointcloud_render_TEST_DEPENDS )
set(pointcloud_render_DOC_DEPENDS )
set(pointcloud_render_URL_WEBSITE "")
set(pointcloud_render_URL_BUGTRACKER "")
set(pointcloud_render_URL_REPOSITORY "")
set(pointcloud_render_DEPRECATED "")