set(_CATKIN_CURRENT_PACKAGE "swarm_data")
set(swarm_data_VERSION "0.0.0")
set(swarm_data_MAINTAINER "user <user@example.com>")
set(swarm_data_PACKAGE_FORMAT "2")
set(swarm_data_BUILD_DEPENDS "roscpp")
set(swarm_data_BUILD_EXPORT_DEPENDS )
set(swarm_data_BUILDTOOL_DEPENDS "catkin")
set(swarm_data_BUILDTOOL_EXPORT_DEPENDS )
set(swarm_data_EXEC_DEPENDS "roscpp")
set(swarm_data_RUN_DEPENDS "roscpp")
set(swarm_data_TEST_DEPENDS )
set(swarm_data_DOC_DEPENDS )
set(swarm_data_URL_WEBSITE "")
set(swarm_data_URL_BUGTRACKER "")
set(swarm_data_URL_REPOSITORY "")
set(swarm_data_DEPRECATED "")