set(_CATKIN_CURRENT_PACKAGE "octomap_world")
set(octomap_world_VERSION "0.0.0")
set(octomap_world_MAINTAINER "user <user@example.com>")
set(octomap_world_PACKAGE_FORMAT "2")
set(octomap_world_BUILD_DEPENDS "roscpp")
set(octomap_world_BUILD_EXPORT_DEPENDS )
set(octomap_world_BUILDTOOL_DEPENDS "catkin")
set(octomap_world_BUILDTOOL_EXPORT_DEPENDS )
set(octomap_world_EXEC_DEPENDS "roscpp")
set(octomap_world_RUN_DEPENDS "roscpp")
set(octomap_world_TEST_DEPENDS )
set(octomap_world_DOC_DEPENDS )
set(octomap_world_URL_WEBSITE "")
set(octomap_world_URL_BUGTRACKER "")
set(octomap_world_URL_REPOSITORY "")
set(octomap_world_DEPRECATED "")