# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from swarm_exp_msgs/DtgBag.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import swarm_exp_msgs.msg

class DtgBag(genpy.Message):
  _md5sum = "0fad25fdf73ad19fd3ef0fed38c94965"
  _type = "swarm_exp_msgs/DtgBag"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# groupe broad cast (quick timer for local or group / slow timer for general)

uint8[] to_uavs
uint32 id
uint8 from_uav

swarm_exp_msgs/DtgHFEdge[] HFedges
swarm_exp_msgs/DtgHHEdge[] HHedges
swarm_exp_msgs/DtgHNode[] Hnodes
swarm_exp_msgs/DtgFNode[] Fnodes 
================================================================================
MSG: swarm_exp_msgs/DtgHFEdge
uint32[] points_idx #low res map
float64 pub_t
uint16 f_id
uint32 h_id
uint8 vp_id
#uint8 hfe_id        #who creates

================================================================================
MSG: swarm_exp_msgs/DtgHHEdge
#uint8 hhe_id        #who creates
#bool erase 
float64 pub_t
uint32[] points_idx #low res map
uint32 head_h_id
uint32 tail_h_id
================================================================================
MSG: swarm_exp_msgs/DtgHNode
uint32 h_id
uint32 pos_idx #low res map
================================================================================
MSG: swarm_exp_msgs/DtgFNode
uint16 f_id
bool alive
uint8[] vp_flags #(alive dead)(alive dead)(alive dead)(alive dead)
uint8 need_help # ask other uav for edge
"""
  __slots__ = ['to_uavs','id','from_uav','HFedges','HHedges','Hnodes','Fnodes']
  _slot_types = ['uint8[]','uint32','uint8','swarm_exp_msgs/DtgHFEdge[]','swarm_exp_msgs/DtgHHEdge[]','swarm_exp_msgs/DtgHNode[]','swarm_exp_msgs/DtgFNode[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       to_uavs,id,from_uav,HFedges,HHedges,Hnodes,Fnodes

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DtgBag, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.to_uavs is None:
        self.to_uavs = b''
      if self.id is None:
        self.id = 0
      if self.from_uav is None:
        self.from_uav = 0
      if self.HFedges is None:
        self.HFedges = []
      if self.HHedges is None:
        self.HHedges = []
      if self.Hnodes is None:
        self.Hnodes = []
      if self.Fnodes is None:
        self.Fnodes = []
    else:
      self.to_uavs = b''
      self.id = 0
      self.from_uav = 0
      self.HFedges = []
      self.HHedges = []
      self.Hnodes = []
      self.Fnodes = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.to_uavs
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_IB().pack(_x.id, _x.from_uav))
      length = len(self.HFedges)
      buff.write(_struct_I.pack(length))
      for val1 in self.HFedges:
        length = len(val1.points_idx)
        buff.write(_struct_I.pack(length))
        pattern = '<%sI'%length
        buff.write(struct.Struct(pattern).pack(*val1.points_idx))
        _x = val1
        buff.write(_get_struct_dHIB().pack(_x.pub_t, _x.f_id, _x.h_id, _x.vp_id))
      length = len(self.HHedges)
      buff.write(_struct_I.pack(length))
      for val1 in self.HHedges:
        _x = val1.pub_t
        buff.write(_get_struct_d().pack(_x))
        length = len(val1.points_idx)
        buff.write(_struct_I.pack(length))
        pattern = '<%sI'%length
        buff.write(struct.Struct(pattern).pack(*val1.points_idx))
        _x = val1
        buff.write(_get_struct_2I().pack(_x.head_h_id, _x.tail_h_id))
      length = len(self.Hnodes)
      buff.write(_struct_I.pack(length))
      for val1 in self.Hnodes:
        _x = val1
        buff.write(_get_struct_2I().pack(_x.h_id, _x.pos_idx))
      length = len(self.Fnodes)
      buff.write(_struct_I.pack(length))
      for val1 in self.Fnodes:
        _x = val1
        buff.write(_get_struct_HB().pack(_x.f_id, _x.alive))
        _x = val1.vp_flags
        length = len(_x)
        # - if encoded as a list instead, serialize as bytes instead of string
        if type(_x) in [list, tuple]:
          buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
        else:
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.need_help
        buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.HFedges is None:
        self.HFedges = None
      if self.HHedges is None:
        self.HHedges = None
      if self.Hnodes is None:
        self.Hnodes = None
      if self.Fnodes is None:
        self.Fnodes = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.to_uavs = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.id, _x.from_uav,) = _get_struct_IB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.HFedges = []
      for i in range(0, length):
        val1 = swarm_exp_msgs.msg.DtgHFEdge()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sI'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.points_idx = s.unpack(str[start:end])
        _x = val1
        start = end
        end += 15
        (_x.pub_t, _x.f_id, _x.h_id, _x.vp_id,) = _get_struct_dHIB().unpack(str[start:end])
        self.HFedges.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.HHedges = []
      for i in range(0, length):
        val1 = swarm_exp_msgs.msg.DtgHHEdge()
        start = end
        end += 8
        (val1.pub_t,) = _get_struct_d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sI'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.points_idx = s.unpack(str[start:end])
        _x = val1
        start = end
        end += 8
        (_x.head_h_id, _x.tail_h_id,) = _get_struct_2I().unpack(str[start:end])
        self.HHedges.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.Hnodes = []
      for i in range(0, length):
        val1 = swarm_exp_msgs.msg.DtgHNode()
        _x = val1
        start = end
        end += 8
        (_x.h_id, _x.pos_idx,) = _get_struct_2I().unpack(str[start:end])
        self.Hnodes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.Fnodes = []
      for i in range(0, length):
        val1 = swarm_exp_msgs.msg.DtgFNode()
        _x = val1
        start = end
        end += 3
        (_x.f_id, _x.alive,) = _get_struct_HB().unpack(str[start:end])
        val1.alive = bool(val1.alive)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        val1.vp_flags = str[start:end]
        start = end
        end += 1
        (val1.need_help,) = _get_struct_B().unpack(str[start:end])
        self.Fnodes.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.to_uavs
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_IB().pack(_x.id, _x.from_uav))
      length = len(self.HFedges)
      buff.write(_struct_I.pack(length))
      for val1 in self.HFedges:
        length = len(val1.points_idx)
        buff.write(_struct_I.pack(length))
        pattern = '<%sI'%length
        buff.write(val1.points_idx.tostring())
        _x = val1
        buff.write(_get_struct_dHIB().pack(_x.pub_t, _x.f_id, _x.h_id, _x.vp_id))
      length = len(self.HHedges)
      buff.write(_struct_I.pack(length))
      for val1 in self.HHedges:
        _x = val1.pub_t
        buff.write(_get_struct_d().pack(_x))
        length = len(val1.points_idx)
        buff.write(_struct_I.pack(length))
        pattern = '<%sI'%length
        buff.write(val1.points_idx.tostring())
        _x = val1
        buff.write(_get_struct_2I().pack(_x.head_h_id, _x.tail_h_id))
      length = len(self.Hnodes)
      buff.write(_struct_I.pack(length))
      for val1 in self.Hnodes:
        _x = val1
        buff.write(_get_struct_2I().pack(_x.h_id, _x.pos_idx))
      length = len(self.Fnodes)
      buff.write(_struct_I.pack(length))
      for val1 in self.Fnodes:
        _x = val1
        buff.write(_get_struct_HB().pack(_x.f_id, _x.alive))
        _x = val1.vp_flags
        length = len(_x)
        # - if encoded as a list instead, serialize as bytes instead of string
        if type(_x) in [list, tuple]:
          buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
        else:
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.need_help
        buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.HFedges is None:
        self.HFedges = None
      if self.HHedges is None:
        self.HHedges = None
      if self.Hnodes is None:
        self.Hnodes = None
      if self.Fnodes is None:
        self.Fnodes = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.to_uavs = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.id, _x.from_uav,) = _get_struct_IB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.HFedges = []
      for i in range(0, length):
        val1 = swarm_exp_msgs.msg.DtgHFEdge()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sI'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.points_idx = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
        _x = val1
        start = end
        end += 15
        (_x.pub_t, _x.f_id, _x.h_id, _x.vp_id,) = _get_struct_dHIB().unpack(str[start:end])
        self.HFedges.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.HHedges = []
      for i in range(0, length):
        val1 = swarm_exp_msgs.msg.DtgHHEdge()
        start = end
        end += 8
        (val1.pub_t,) = _get_struct_d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sI'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.points_idx = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
        _x = val1
        start = end
        end += 8
        (_x.head_h_id, _x.tail_h_id,) = _get_struct_2I().unpack(str[start:end])
        self.HHedges.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.Hnodes = []
      for i in range(0, length):
        val1 = swarm_exp_msgs.msg.DtgHNode()
        _x = val1
        start = end
        end += 8
        (_x.h_id, _x.pos_idx,) = _get_struct_2I().unpack(str[start:end])
        self.Hnodes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.Fnodes = []
      for i in range(0, length):
        val1 = swarm_exp_msgs.msg.DtgFNode()
        _x = val1
        start = end
        end += 3
        (_x.f_id, _x.alive,) = _get_struct_HB().unpack(str[start:end])
        val1.alive = bool(val1.alive)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        val1.vp_flags = str[start:end]
        start = end
        end += 1
        (val1.need_help,) = _get_struct_B().unpack(str[start:end])
        self.Fnodes.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_HB = None
def _get_struct_HB():
    global _struct_HB
    if _struct_HB is None:
        _struct_HB = struct.Struct("<HB")
    return _struct_HB
_struct_IB = None
def _get_struct_IB():
    global _struct_IB
    if _struct_IB is None:
        _struct_IB = struct.Struct("<IB")
    return _struct_IB
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
_struct_dHIB = None
def _get_struct_dHIB():
    global _struct_dHIB
    if _struct_dHIB is None:
        _struct_dHIB = struct.Struct("<dHIB")
    return _struct_dHIB
