# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from swarm_exp_msgs/DtgHFEdge.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DtgHFEdge(genpy.Message):
  _md5sum = "e9f0be3eb0a7ce0d70ee65a834e21ddf"
  _type = "swarm_exp_msgs/DtgHFEdge"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint32[] points_idx #low res map
float64 pub_t
uint16 f_id
uint32 h_id
uint8 vp_id
#uint8 hfe_id        #who creates
"""
  __slots__ = ['points_idx','pub_t','f_id','h_id','vp_id']
  _slot_types = ['uint32[]','float64','uint16','uint32','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       points_idx,pub_t,f_id,h_id,vp_id

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DtgHFEdge, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.points_idx is None:
        self.points_idx = []
      if self.pub_t is None:
        self.pub_t = 0.
      if self.f_id is None:
        self.f_id = 0
      if self.h_id is None:
        self.h_id = 0
      if self.vp_id is None:
        self.vp_id = 0
    else:
      self.points_idx = []
      self.pub_t = 0.
      self.f_id = 0
      self.h_id = 0
      self.vp_id = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.points_idx)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.Struct(pattern).pack(*self.points_idx))
      _x = self
      buff.write(_get_struct_dHIB().pack(_x.pub_t, _x.f_id, _x.h_id, _x.vp_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.points_idx = s.unpack(str[start:end])
      _x = self
      start = end
      end += 15
      (_x.pub_t, _x.f_id, _x.h_id, _x.vp_id,) = _get_struct_dHIB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.points_idx)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.points_idx.tostring())
      _x = self
      buff.write(_get_struct_dHIB().pack(_x.pub_t, _x.f_id, _x.h_id, _x.vp_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.points_idx = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      _x = self
      start = end
      end += 15
      (_x.pub_t, _x.f_id, _x.h_id, _x.vp_id,) = _get_struct_dHIB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_dHIB = None
def _get_struct_dHIB():
    global _struct_dHIB
    if _struct_dHIB is None:
        _struct_dHIB = struct.Struct("<dHIB")
    return _struct_dHIB
