# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from swarm_exp_msgs/DtgFFEdge.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DtgFFEdge(genpy.Message):
  _md5sum = "764ef8eb22d76355c9c291bdaa1ae595"
  _type = "swarm_exp_msgs/DtgFFEdge"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint16 head_f_id
uint16 tail_f_id
uint32[] points_idx #low res map

uint8 head_v_id #viewpoint id of head fn
uint8 tail_v_id #viewpoint id of tail fn
uint8 ffe_id    #who creates
"""
  __slots__ = ['head_f_id','tail_f_id','points_idx','head_v_id','tail_v_id','ffe_id']
  _slot_types = ['uint16','uint16','uint32[]','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       head_f_id,tail_f_id,points_idx,head_v_id,tail_v_id,ffe_id

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DtgFFEdge, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.head_f_id is None:
        self.head_f_id = 0
      if self.tail_f_id is None:
        self.tail_f_id = 0
      if self.points_idx is None:
        self.points_idx = []
      if self.head_v_id is None:
        self.head_v_id = 0
      if self.tail_v_id is None:
        self.tail_v_id = 0
      if self.ffe_id is None:
        self.ffe_id = 0
    else:
      self.head_f_id = 0
      self.tail_f_id = 0
      self.points_idx = []
      self.head_v_id = 0
      self.tail_v_id = 0
      self.ffe_id = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2H().pack(_x.head_f_id, _x.tail_f_id))
      length = len(self.points_idx)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.Struct(pattern).pack(*self.points_idx))
      _x = self
      buff.write(_get_struct_3B().pack(_x.head_v_id, _x.tail_v_id, _x.ffe_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.head_f_id, _x.tail_f_id,) = _get_struct_2H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.points_idx = s.unpack(str[start:end])
      _x = self
      start = end
      end += 3
      (_x.head_v_id, _x.tail_v_id, _x.ffe_id,) = _get_struct_3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2H().pack(_x.head_f_id, _x.tail_f_id))
      length = len(self.points_idx)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.points_idx.tostring())
      _x = self
      buff.write(_get_struct_3B().pack(_x.head_v_id, _x.tail_v_id, _x.ffe_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.head_f_id, _x.tail_f_id,) = _get_struct_2H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.points_idx = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      _x = self
      start = end
      end += 3
      (_x.head_v_id, _x.tail_v_id, _x.ffe_id,) = _get_struct_3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2H = None
def _get_struct_2H():
    global _struct_2H
    if _struct_2H is None:
        _struct_2H = struct.Struct("<2H")
    return _struct_2H
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
