# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from swarm_exp_msgs/DtgHHEdge.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DtgHHEdge(genpy.Message):
  _md5sum = "f28c77b458771baddef5547b4e2a8c2d"
  _type = "swarm_exp_msgs/DtgHHEdge"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#uint8 hhe_id        #who creates
#bool erase 
float64 pub_t
uint32[] points_idx #low res map
uint32 head_h_id
uint32 tail_h_id"""
  __slots__ = ['pub_t','points_idx','head_h_id','tail_h_id']
  _slot_types = ['float64','uint32[]','uint32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pub_t,points_idx,head_h_id,tail_h_id

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DtgHHEdge, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pub_t is None:
        self.pub_t = 0.
      if self.points_idx is None:
        self.points_idx = []
      if self.head_h_id is None:
        self.head_h_id = 0
      if self.tail_h_id is None:
        self.tail_h_id = 0
    else:
      self.pub_t = 0.
      self.points_idx = []
      self.head_h_id = 0
      self.tail_h_id = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.pub_t
      buff.write(_get_struct_d().pack(_x))
      length = len(self.points_idx)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.Struct(pattern).pack(*self.points_idx))
      _x = self
      buff.write(_get_struct_2I().pack(_x.head_h_id, _x.tail_h_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 8
      (self.pub_t,) = _get_struct_d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.points_idx = s.unpack(str[start:end])
      _x = self
      start = end
      end += 8
      (_x.head_h_id, _x.tail_h_id,) = _get_struct_2I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.pub_t
      buff.write(_get_struct_d().pack(_x))
      length = len(self.points_idx)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.points_idx.tostring())
      _x = self
      buff.write(_get_struct_2I().pack(_x.head_h_id, _x.tail_h_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 8
      (self.pub_t,) = _get_struct_d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.points_idx = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      _x = self
      start = end
      end += 8
      (_x.head_h_id, _x.tail_h_id,) = _get_struct_2I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
