# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from swarm_exp_msgs/GroupCommandReq.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GroupCommandReq(genpy.Message):
  _md5sum = "8907e16fca4b37e09a5750aaba75e3cc"
  _type = "swarm_exp_msgs/GroupCommandReq"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# inside group, from trooper (Quick timmer)
uint8[] to_uavs
# uint8 from_uav

float64 cur_t
# 1: Departure; 2: Help, 3: switch trooper
uint8 dispatch_type 

# departure
uint32[] departure_EROIs
uint8 departure_status #0: trooper; 1: infantry

#help
uint8 helped_group_id


"""
  __slots__ = ['to_uavs','cur_t','dispatch_type','departure_EROIs','departure_status','helped_group_id']
  _slot_types = ['uint8[]','float64','uint8','uint32[]','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       to_uavs,cur_t,dispatch_type,departure_EROIs,departure_status,helped_group_id

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GroupCommandReq, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.to_uavs is None:
        self.to_uavs = b''
      if self.cur_t is None:
        self.cur_t = 0.
      if self.dispatch_type is None:
        self.dispatch_type = 0
      if self.departure_EROIs is None:
        self.departure_EROIs = []
      if self.departure_status is None:
        self.departure_status = 0
      if self.helped_group_id is None:
        self.helped_group_id = 0
    else:
      self.to_uavs = b''
      self.cur_t = 0.
      self.dispatch_type = 0
      self.departure_EROIs = []
      self.departure_status = 0
      self.helped_group_id = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.to_uavs
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_dB().pack(_x.cur_t, _x.dispatch_type))
      length = len(self.departure_EROIs)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.Struct(pattern).pack(*self.departure_EROIs))
      _x = self
      buff.write(_get_struct_2B().pack(_x.departure_status, _x.helped_group_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.to_uavs = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.cur_t, _x.dispatch_type,) = _get_struct_dB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.departure_EROIs = s.unpack(str[start:end])
      _x = self
      start = end
      end += 2
      (_x.departure_status, _x.helped_group_id,) = _get_struct_2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.to_uavs
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_dB().pack(_x.cur_t, _x.dispatch_type))
      length = len(self.departure_EROIs)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.departure_EROIs.tostring())
      _x = self
      buff.write(_get_struct_2B().pack(_x.departure_status, _x.helped_group_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.to_uavs = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.cur_t, _x.dispatch_type,) = _get_struct_dB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.departure_EROIs = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      _x = self
      start = end
      end += 2
      (_x.departure_status, _x.helped_group_id,) = _get_struct_2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
_struct_dB = None
def _get_struct_dB():
    global _struct_dB
    if _struct_dB is None:
        _struct_dB = struct.Struct("<dB")
    return _struct_dB
