# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from swarm_exp_msgs/GroupState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GroupState(genpy.Message):
  _md5sum = "17f63ea80422701593a5c33c707b7615"
  _type = "swarm_exp_msgs/GroupState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# inter group broad cast (slow timer)
uint8[] to_uavs
uint8 from_uav

float64 cur_t
uint8 group_size
uint32[] trooper_targets
uint16 potential #calculated unknown space number, for helpers
uint16 coverage_work_load
uint8 state # 0000 00(need help)(exp/cover)

"""
  __slots__ = ['to_uavs','from_uav','cur_t','group_size','trooper_targets','potential','coverage_work_load','state']
  _slot_types = ['uint8[]','uint8','float64','uint8','uint32[]','uint16','uint16','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       to_uavs,from_uav,cur_t,group_size,trooper_targets,potential,coverage_work_load,state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GroupState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.to_uavs is None:
        self.to_uavs = b''
      if self.from_uav is None:
        self.from_uav = 0
      if self.cur_t is None:
        self.cur_t = 0.
      if self.group_size is None:
        self.group_size = 0
      if self.trooper_targets is None:
        self.trooper_targets = []
      if self.potential is None:
        self.potential = 0
      if self.coverage_work_load is None:
        self.coverage_work_load = 0
      if self.state is None:
        self.state = 0
    else:
      self.to_uavs = b''
      self.from_uav = 0
      self.cur_t = 0.
      self.group_size = 0
      self.trooper_targets = []
      self.potential = 0
      self.coverage_work_load = 0
      self.state = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.to_uavs
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BdB().pack(_x.from_uav, _x.cur_t, _x.group_size))
      length = len(self.trooper_targets)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.Struct(pattern).pack(*self.trooper_targets))
      _x = self
      buff.write(_get_struct_2HB().pack(_x.potential, _x.coverage_work_load, _x.state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.to_uavs = str[start:end]
      _x = self
      start = end
      end += 10
      (_x.from_uav, _x.cur_t, _x.group_size,) = _get_struct_BdB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.trooper_targets = s.unpack(str[start:end])
      _x = self
      start = end
      end += 5
      (_x.potential, _x.coverage_work_load, _x.state,) = _get_struct_2HB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.to_uavs
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BdB().pack(_x.from_uav, _x.cur_t, _x.group_size))
      length = len(self.trooper_targets)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.trooper_targets.tostring())
      _x = self
      buff.write(_get_struct_2HB().pack(_x.potential, _x.coverage_work_load, _x.state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.to_uavs = str[start:end]
      _x = self
      start = end
      end += 10
      (_x.from_uav, _x.cur_t, _x.group_size,) = _get_struct_BdB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.trooper_targets = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      _x = self
      start = end
      end += 5
      (_x.potential, _x.coverage_work_load, _x.state,) = _get_struct_2HB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2HB = None
def _get_struct_2HB():
    global _struct_2HB
    if _struct_2HB is None:
        _struct_2HB = struct.Struct("<2HB")
    return _struct_2HB
_struct_BdB = None
def _get_struct_BdB():
    global _struct_BdB
    if _struct_BdB is None:
        _struct_BdB = struct.Struct("<BdB")
    return _struct_BdB
