# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from swarm_exp_msgs/LocalTraj.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class LocalTraj(genpy.Message):
  _md5sum = "0b2ad7fbcf01f3397172ee31bee3cc0b"
  _type = "swarm_exp_msgs/LocalTraj"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 from_uav
uint8[] to_uavs

int8 state

geometry_msgs/Point recover_pt

float64 start_t
int8 order_p
float32[] t_p
geometry_msgs/Point[] coef_p

int8 order_yaw
float32[] t_yaw
float32[] coef_yaw

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['from_uav','to_uavs','state','recover_pt','start_t','order_p','t_p','coef_p','order_yaw','t_yaw','coef_yaw']
  _slot_types = ['uint8','uint8[]','int8','geometry_msgs/Point','float64','int8','float32[]','geometry_msgs/Point[]','int8','float32[]','float32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       from_uav,to_uavs,state,recover_pt,start_t,order_p,t_p,coef_p,order_yaw,t_yaw,coef_yaw

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LocalTraj, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.from_uav is None:
        self.from_uav = 0
      if self.to_uavs is None:
        self.to_uavs = b''
      if self.state is None:
        self.state = 0
      if self.recover_pt is None:
        self.recover_pt = geometry_msgs.msg.Point()
      if self.start_t is None:
        self.start_t = 0.
      if self.order_p is None:
        self.order_p = 0
      if self.t_p is None:
        self.t_p = []
      if self.coef_p is None:
        self.coef_p = []
      if self.order_yaw is None:
        self.order_yaw = 0
      if self.t_yaw is None:
        self.t_yaw = []
      if self.coef_yaw is None:
        self.coef_yaw = []
    else:
      self.from_uav = 0
      self.to_uavs = b''
      self.state = 0
      self.recover_pt = geometry_msgs.msg.Point()
      self.start_t = 0.
      self.order_p = 0
      self.t_p = []
      self.coef_p = []
      self.order_yaw = 0
      self.t_yaw = []
      self.coef_yaw = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.from_uav
      buff.write(_get_struct_B().pack(_x))
      _x = self.to_uavs
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_b4db().pack(_x.state, _x.recover_pt.x, _x.recover_pt.y, _x.recover_pt.z, _x.start_t, _x.order_p))
      length = len(self.t_p)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.t_p))
      length = len(self.coef_p)
      buff.write(_struct_I.pack(length))
      for val1 in self.coef_p:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      _x = self.order_yaw
      buff.write(_get_struct_b().pack(_x))
      length = len(self.t_yaw)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.t_yaw))
      length = len(self.coef_yaw)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.coef_yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.recover_pt is None:
        self.recover_pt = geometry_msgs.msg.Point()
      if self.coef_p is None:
        self.coef_p = None
      end = 0
      start = end
      end += 1
      (self.from_uav,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.to_uavs = str[start:end]
      _x = self
      start = end
      end += 34
      (_x.state, _x.recover_pt.x, _x.recover_pt.y, _x.recover_pt.z, _x.start_t, _x.order_p,) = _get_struct_b4db().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.t_p = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.coef_p = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.coef_p.append(val1)
      start = end
      end += 1
      (self.order_yaw,) = _get_struct_b().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.t_yaw = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.coef_yaw = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.from_uav
      buff.write(_get_struct_B().pack(_x))
      _x = self.to_uavs
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_b4db().pack(_x.state, _x.recover_pt.x, _x.recover_pt.y, _x.recover_pt.z, _x.start_t, _x.order_p))
      length = len(self.t_p)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.t_p.tostring())
      length = len(self.coef_p)
      buff.write(_struct_I.pack(length))
      for val1 in self.coef_p:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      _x = self.order_yaw
      buff.write(_get_struct_b().pack(_x))
      length = len(self.t_yaw)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.t_yaw.tostring())
      length = len(self.coef_yaw)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.coef_yaw.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.recover_pt is None:
        self.recover_pt = geometry_msgs.msg.Point()
      if self.coef_p is None:
        self.coef_p = None
      end = 0
      start = end
      end += 1
      (self.from_uav,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.to_uavs = str[start:end]
      _x = self
      start = end
      end += 34
      (_x.state, _x.recover_pt.x, _x.recover_pt.y, _x.recover_pt.z, _x.start_t, _x.order_p,) = _get_struct_b4db().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.t_p = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.coef_p = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.coef_p.append(val1)
      start = end
      end += 1
      (self.order_yaw,) = _get_struct_b().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.t_yaw = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.coef_yaw = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_b = None
def _get_struct_b():
    global _struct_b
    if _struct_b is None:
        _struct_b = struct.Struct("<b")
    return _struct_b
_struct_b4db = None
def _get_struct_b4db():
    global _struct_b4db
    if _struct_b4db is None:
        _struct_b4db = struct.Struct("<b4db")
    return _struct_b4db
