set(_CATKIN_CURRENT_PACKAGE "NKPlanner")
set(NKPlanner_VERSION "0.0.0")
set(NKPlanner_MAINTAINER "user <user@example.com>")
set(NKPlanner_PACKAGE_FORMAT "2")
set(NKPlanner_BUILD_DEPENDS "roscpp")
set(NKPlanner_BUILD_EXPORT_DEPENDS )
set(NKPlanner_BUILDTOOL_DEPENDS "catkin")
set(NKPlanner_BUILDTOOL_EXPORT_DEPENDS )
set(NKPlanner_EXEC_DEPENDS "roscpp")
set(NKPlanner_RUN_DEPENDS "roscpp")
set(NKPlanner_TEST_DEPENDS )
set(NKPlanner_DOC_DEPENDS )
set(NKPlanner_URL_WEBSITE "")
set(NKPlanner_URL_BUGTRACKER "")
set(NKPlanner_URL_REPOSITORY "")
set(NKPlanner_DEPRECATED "")