# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from exp_comm_msgs/SwarmJobC.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SwarmJobC(genpy.Message):
  _md5sum = "e25c09eda529caf2748eb82a8886575b"
  _type = "exp_comm_msgs/SwarmJobC"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 pub_t
uint8 from_uav
uint8 JobState #0000 0(no job = 0/ new job = 1)(finish = 1)(local = 0/ global = 1)
int32  target_fn
int32 target_hn
float32 dist_to_fn
float32 dist_to_hn


"""
  __slots__ = ['pub_t','from_uav','JobState','target_fn','target_hn','dist_to_fn','dist_to_hn']
  _slot_types = ['float64','uint8','uint8','int32','int32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pub_t,from_uav,JobState,target_fn,target_hn,dist_to_fn,dist_to_hn

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SwarmJobC, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pub_t is None:
        self.pub_t = 0.
      if self.from_uav is None:
        self.from_uav = 0
      if self.JobState is None:
        self.JobState = 0
      if self.target_fn is None:
        self.target_fn = 0
      if self.target_hn is None:
        self.target_hn = 0
      if self.dist_to_fn is None:
        self.dist_to_fn = 0.
      if self.dist_to_hn is None:
        self.dist_to_hn = 0.
    else:
      self.pub_t = 0.
      self.from_uav = 0
      self.JobState = 0
      self.target_fn = 0
      self.target_hn = 0
      self.dist_to_fn = 0.
      self.dist_to_hn = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_d2B2i2f().pack(_x.pub_t, _x.from_uav, _x.JobState, _x.target_fn, _x.target_hn, _x.dist_to_fn, _x.dist_to_hn))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 26
      (_x.pub_t, _x.from_uav, _x.JobState, _x.target_fn, _x.target_hn, _x.dist_to_fn, _x.dist_to_hn,) = _get_struct_d2B2i2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_d2B2i2f().pack(_x.pub_t, _x.from_uav, _x.JobState, _x.target_fn, _x.target_hn, _x.dist_to_fn, _x.dist_to_hn))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 26
      (_x.pub_t, _x.from_uav, _x.JobState, _x.target_fn, _x.target_hn, _x.dist_to_fn, _x.dist_to_hn,) = _get_struct_d2B2i2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_d2B2i2f = None
def _get_struct_d2B2i2f():
    global _struct_d2B2i2f
    if _struct_d2B2i2f is None:
        _struct_d2B2i2f = struct.Struct("<d2B2i2f")
    return _struct_d2B2i2f
