# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from exp_comm_msgs/SwarmStateC.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SwarmStateC(genpy.Message):
  _md5sum = "11fc39f21c102f3f37a28c1e4132b63e"
  _type = "exp_comm_msgs/SwarmStateC"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 pub_t
uint8 from_uav
uint8 flags #0000 000(quick communication) 
uint16[]  local_fn
float32[] dist_to_local_fn

uint16[]  connect_fn
float32[] dist_to_connect_fn

uint32[]  connect_hn
uint32[]  hn_pos_idx
float32[] dist_to_connect_hn  

"""
  __slots__ = ['pub_t','from_uav','flags','local_fn','dist_to_local_fn','connect_fn','dist_to_connect_fn','connect_hn','hn_pos_idx','dist_to_connect_hn']
  _slot_types = ['float64','uint8','uint8','uint16[]','float32[]','uint16[]','float32[]','uint32[]','uint32[]','float32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pub_t,from_uav,flags,local_fn,dist_to_local_fn,connect_fn,dist_to_connect_fn,connect_hn,hn_pos_idx,dist_to_connect_hn

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SwarmStateC, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pub_t is None:
        self.pub_t = 0.
      if self.from_uav is None:
        self.from_uav = 0
      if self.flags is None:
        self.flags = 0
      if self.local_fn is None:
        self.local_fn = []
      if self.dist_to_local_fn is None:
        self.dist_to_local_fn = []
      if self.connect_fn is None:
        self.connect_fn = []
      if self.dist_to_connect_fn is None:
        self.dist_to_connect_fn = []
      if self.connect_hn is None:
        self.connect_hn = []
      if self.hn_pos_idx is None:
        self.hn_pos_idx = []
      if self.dist_to_connect_hn is None:
        self.dist_to_connect_hn = []
    else:
      self.pub_t = 0.
      self.from_uav = 0
      self.flags = 0
      self.local_fn = []
      self.dist_to_local_fn = []
      self.connect_fn = []
      self.dist_to_connect_fn = []
      self.connect_hn = []
      self.hn_pos_idx = []
      self.dist_to_connect_hn = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_d2B().pack(_x.pub_t, _x.from_uav, _x.flags))
      length = len(self.local_fn)
      buff.write(_struct_I.pack(length))
      pattern = '<%sH'%length
      buff.write(struct.Struct(pattern).pack(*self.local_fn))
      length = len(self.dist_to_local_fn)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.dist_to_local_fn))
      length = len(self.connect_fn)
      buff.write(_struct_I.pack(length))
      pattern = '<%sH'%length
      buff.write(struct.Struct(pattern).pack(*self.connect_fn))
      length = len(self.dist_to_connect_fn)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.dist_to_connect_fn))
      length = len(self.connect_hn)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.Struct(pattern).pack(*self.connect_hn))
      length = len(self.hn_pos_idx)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.Struct(pattern).pack(*self.hn_pos_idx))
      length = len(self.dist_to_connect_hn)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.dist_to_connect_hn))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.pub_t, _x.from_uav, _x.flags,) = _get_struct_d2B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sH'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.local_fn = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.dist_to_local_fn = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sH'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.connect_fn = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.dist_to_connect_fn = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.connect_hn = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.hn_pos_idx = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.dist_to_connect_hn = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_d2B().pack(_x.pub_t, _x.from_uav, _x.flags))
      length = len(self.local_fn)
      buff.write(_struct_I.pack(length))
      pattern = '<%sH'%length
      buff.write(self.local_fn.tostring())
      length = len(self.dist_to_local_fn)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.dist_to_local_fn.tostring())
      length = len(self.connect_fn)
      buff.write(_struct_I.pack(length))
      pattern = '<%sH'%length
      buff.write(self.connect_fn.tostring())
      length = len(self.dist_to_connect_fn)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.dist_to_connect_fn.tostring())
      length = len(self.connect_hn)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.connect_hn.tostring())
      length = len(self.hn_pos_idx)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.hn_pos_idx.tostring())
      length = len(self.dist_to_connect_hn)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.dist_to_connect_hn.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.pub_t, _x.from_uav, _x.flags,) = _get_struct_d2B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sH'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.local_fn = numpy.frombuffer(str[start:end], dtype=numpy.uint16, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.dist_to_local_fn = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sH'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.connect_fn = numpy.frombuffer(str[start:end], dtype=numpy.uint16, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.dist_to_connect_fn = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.connect_hn = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.hn_pos_idx = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.dist_to_connect_hn = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_d2B = None
def _get_struct_d2B():
    global _struct_d2B
    if _struct_d2B is None:
        _struct_d2B = struct.Struct("<d2B")
    return _struct_d2B
