# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from exp_comm_msgs/SwarmTrajC.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class SwarmTrajC(genpy.Message):
  _md5sum = "b412e83c14c239c5f9f2ca748f0bead0"
  _type = "exp_comm_msgs/SwarmTrajC"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 pub_t

uint8 id

float64 start_t
int8 order_p
float32[] t_p
geometry_msgs/Point[] coef_p

# int8 order_yaw
# float32[] t_yaw
# float32[] coef_yaw
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['pub_t','id','start_t','order_p','t_p','coef_p']
  _slot_types = ['float64','uint8','float64','int8','float32[]','geometry_msgs/Point[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pub_t,id,start_t,order_p,t_p,coef_p

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SwarmTrajC, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pub_t is None:
        self.pub_t = 0.
      if self.id is None:
        self.id = 0
      if self.start_t is None:
        self.start_t = 0.
      if self.order_p is None:
        self.order_p = 0
      if self.t_p is None:
        self.t_p = []
      if self.coef_p is None:
        self.coef_p = []
    else:
      self.pub_t = 0.
      self.id = 0
      self.start_t = 0.
      self.order_p = 0
      self.t_p = []
      self.coef_p = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_dBdb().pack(_x.pub_t, _x.id, _x.start_t, _x.order_p))
      length = len(self.t_p)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.t_p))
      length = len(self.coef_p)
      buff.write(_struct_I.pack(length))
      for val1 in self.coef_p:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.coef_p is None:
        self.coef_p = None
      end = 0
      _x = self
      start = end
      end += 18
      (_x.pub_t, _x.id, _x.start_t, _x.order_p,) = _get_struct_dBdb().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.t_p = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.coef_p = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.coef_p.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_dBdb().pack(_x.pub_t, _x.id, _x.start_t, _x.order_p))
      length = len(self.t_p)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.t_p.tostring())
      length = len(self.coef_p)
      buff.write(_struct_I.pack(length))
      for val1 in self.coef_p:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.coef_p is None:
        self.coef_p = None
      end = 0
      _x = self
      start = end
      end += 18
      (_x.pub_t, _x.id, _x.start_t, _x.order_p,) = _get_struct_dBdb().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.t_p = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.coef_p = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.coef_p.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_dBdb = None
def _get_struct_dBdb():
    global _struct_dBdb
    if _struct_dBdb is None:
        _struct_dBdb = struct.Struct("<dBdb")
    return _struct_dBdb
