// Generated by gencpp from file swarm_exp_msgs/DtgBag.msg
// DO NOT EDIT!


#ifndef SWARM_EXP_MSGS_MESSAGE_DTGBAG_H
#define SWARM_EXP_MSGS_MESSAGE_DTGBAG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <swarm_exp_msgs/DtgHFEdge.h>
#include <swarm_exp_msgs/DtgHHEdge.h>
#include <swarm_exp_msgs/DtgHNode.h>
#include <swarm_exp_msgs/DtgFNode.h>

namespace swarm_exp_msgs
{
template <class ContainerAllocator>
struct DtgBag_
{
  typedef DtgBag_<ContainerAllocator> Type;

  DtgBag_()
    : to_uavs()
    , id(0)
    , from_uav(0)
    , HFedges()
    , HHedges()
    , Hnodes()
    , Fnodes()  {
    }
  DtgBag_(const ContainerAllocator& _alloc)
    : to_uavs(_alloc)
    , id(0)
    , from_uav(0)
    , HFedges(_alloc)
    , HHedges(_alloc)
    , Hnodes(_alloc)
    , Fnodes(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _to_uavs_type;
  _to_uavs_type to_uavs;

   typedef uint32_t _id_type;
  _id_type id;

   typedef uint8_t _from_uav_type;
  _from_uav_type from_uav;

   typedef std::vector< ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator> >> _HFedges_type;
  _HFedges_type HFedges;

   typedef std::vector< ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator> >> _HHedges_type;
  _HHedges_type HHedges;

   typedef std::vector< ::swarm_exp_msgs::DtgHNode_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::swarm_exp_msgs::DtgHNode_<ContainerAllocator> >> _Hnodes_type;
  _Hnodes_type Hnodes;

   typedef std::vector< ::swarm_exp_msgs::DtgFNode_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::swarm_exp_msgs::DtgFNode_<ContainerAllocator> >> _Fnodes_type;
  _Fnodes_type Fnodes;





  typedef boost::shared_ptr< ::swarm_exp_msgs::DtgBag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_exp_msgs::DtgBag_<ContainerAllocator> const> ConstPtr;

}; // struct DtgBag_

typedef ::swarm_exp_msgs::DtgBag_<std::allocator<void> > DtgBag;

typedef boost::shared_ptr< ::swarm_exp_msgs::DtgBag > DtgBagPtr;
typedef boost::shared_ptr< ::swarm_exp_msgs::DtgBag const> DtgBagConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_exp_msgs::DtgBag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_exp_msgs::DtgBag_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_exp_msgs::DtgBag_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::DtgBag_<ContainerAllocator2> & rhs)
{
  return lhs.to_uavs == rhs.to_uavs &&
    lhs.id == rhs.id &&
    lhs.from_uav == rhs.from_uav &&
    lhs.HFedges == rhs.HFedges &&
    lhs.HHedges == rhs.HHedges &&
    lhs.Hnodes == rhs.Hnodes &&
    lhs.Fnodes == rhs.Fnodes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_exp_msgs::DtgBag_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::DtgBag_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_exp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::DtgBag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::DtgBag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::DtgBag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::DtgBag_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::DtgBag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::DtgBag_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_exp_msgs::DtgBag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0fad25fdf73ad19fd3ef0fed38c94965";
  }

  static const char* value(const ::swarm_exp_msgs::DtgBag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0fad25fdf73ad19fULL;
  static const uint64_t static_value2 = 0xd3ef0fed38c94965ULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_exp_msgs::DtgBag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_exp_msgs/DtgBag";
  }

  static const char* value(const ::swarm_exp_msgs::DtgBag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_exp_msgs::DtgBag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# groupe broad cast (quick timer for local or group / slow timer for general)\n"
"\n"
"uint8[] to_uavs\n"
"uint32 id\n"
"uint8 from_uav\n"
"\n"
"swarm_exp_msgs/DtgHFEdge[] HFedges\n"
"swarm_exp_msgs/DtgHHEdge[] HHedges\n"
"swarm_exp_msgs/DtgHNode[] Hnodes\n"
"swarm_exp_msgs/DtgFNode[] Fnodes \n"
"================================================================================\n"
"MSG: swarm_exp_msgs/DtgHFEdge\n"
"uint32[] points_idx #low res map\n"
"float64 pub_t\n"
"uint16 f_id\n"
"uint32 h_id\n"
"uint8 vp_id\n"
"#uint8 hfe_id        #who creates\n"
"\n"
"================================================================================\n"
"MSG: swarm_exp_msgs/DtgHHEdge\n"
"#uint8 hhe_id        #who creates\n"
"#bool erase \n"
"float64 pub_t\n"
"uint32[] points_idx #low res map\n"
"uint32 head_h_id\n"
"uint32 tail_h_id\n"
"================================================================================\n"
"MSG: swarm_exp_msgs/DtgHNode\n"
"uint32 h_id\n"
"uint32 pos_idx #low res map\n"
"================================================================================\n"
"MSG: swarm_exp_msgs/DtgFNode\n"
"uint16 f_id\n"
"bool alive\n"
"uint8[] vp_flags #(alive dead)(alive dead)(alive dead)(alive dead)\n"
"uint8 need_help # ask other uav for edge\n"
;
  }

  static const char* value(const ::swarm_exp_msgs::DtgBag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_exp_msgs::DtgBag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.to_uavs);
      stream.next(m.id);
      stream.next(m.from_uav);
      stream.next(m.HFedges);
      stream.next(m.HHedges);
      stream.next(m.Hnodes);
      stream.next(m.Fnodes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DtgBag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_exp_msgs::DtgBag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_exp_msgs::DtgBag_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "to_uavs: ";
    if (v.to_uavs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.to_uavs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.to_uavs[i]);
    }
    if (v.to_uavs.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "from_uav: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.from_uav);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "HFedges: ";
    if (v.HFedges.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.HFedges.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.HFedges[i]);
    }
    if (v.HFedges.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "HHedges: ";
    if (v.HHedges.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.HHedges.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.HHedges[i]);
    }
    if (v.HHedges.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Hnodes: ";
    if (v.Hnodes.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.Hnodes.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::swarm_exp_msgs::DtgHNode_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.Hnodes[i]);
    }
    if (v.Hnodes.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Fnodes: ";
    if (v.Fnodes.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.Fnodes.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::swarm_exp_msgs::DtgFNode_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.Fnodes[i]);
    }
    if (v.Fnodes.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_EXP_MSGS_MESSAGE_DTGBAG_H
