// Generated by gencpp from file swarm_exp_msgs/DtgFNode.msg
// DO NOT EDIT!


#ifndef SWARM_EXP_MSGS_MESSAGE_DTGFNODE_H
#define SWARM_EXP_MSGS_MESSAGE_DTGFNODE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace swarm_exp_msgs
{
template <class ContainerAllocator>
struct DtgFNode_
{
  typedef DtgFNode_<ContainerAllocator> Type;

  DtgFNode_()
    : f_id(0)
    , alive(false)
    , vp_flags()
    , need_help(0)  {
    }
  DtgFNode_(const ContainerAllocator& _alloc)
    : f_id(0)
    , alive(false)
    , vp_flags(_alloc)
    , need_help(0)  {
  (void)_alloc;
    }



   typedef uint16_t _f_id_type;
  _f_id_type f_id;

   typedef uint8_t _alive_type;
  _alive_type alive;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _vp_flags_type;
  _vp_flags_type vp_flags;

   typedef uint8_t _need_help_type;
  _need_help_type need_help;





  typedef boost::shared_ptr< ::swarm_exp_msgs::DtgFNode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_exp_msgs::DtgFNode_<ContainerAllocator> const> ConstPtr;

}; // struct DtgFNode_

typedef ::swarm_exp_msgs::DtgFNode_<std::allocator<void> > DtgFNode;

typedef boost::shared_ptr< ::swarm_exp_msgs::DtgFNode > DtgFNodePtr;
typedef boost::shared_ptr< ::swarm_exp_msgs::DtgFNode const> DtgFNodeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_exp_msgs::DtgFNode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_exp_msgs::DtgFNode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_exp_msgs::DtgFNode_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::DtgFNode_<ContainerAllocator2> & rhs)
{
  return lhs.f_id == rhs.f_id &&
    lhs.alive == rhs.alive &&
    lhs.vp_flags == rhs.vp_flags &&
    lhs.need_help == rhs.need_help;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_exp_msgs::DtgFNode_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::DtgFNode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_exp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::DtgFNode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::DtgFNode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::DtgFNode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::DtgFNode_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::DtgFNode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::DtgFNode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_exp_msgs::DtgFNode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f35023aa28359878229c76466f958b4c";
  }

  static const char* value(const ::swarm_exp_msgs::DtgFNode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf35023aa28359878ULL;
  static const uint64_t static_value2 = 0x229c76466f958b4cULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_exp_msgs::DtgFNode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_exp_msgs/DtgFNode";
  }

  static const char* value(const ::swarm_exp_msgs::DtgFNode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_exp_msgs::DtgFNode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 f_id\n"
"bool alive\n"
"uint8[] vp_flags #(alive dead)(alive dead)(alive dead)(alive dead)\n"
"uint8 need_help # ask other uav for edge\n"
;
  }

  static const char* value(const ::swarm_exp_msgs::DtgFNode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_exp_msgs::DtgFNode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.f_id);
      stream.next(m.alive);
      stream.next(m.vp_flags);
      stream.next(m.need_help);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DtgFNode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_exp_msgs::DtgFNode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_exp_msgs::DtgFNode_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "f_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.f_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "alive: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.alive);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vp_flags: ";
    if (v.vp_flags.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.vp_flags.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.vp_flags[i]);
    }
    if (v.vp_flags.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "need_help: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.need_help);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_EXP_MSGS_MESSAGE_DTGFNODE_H
