// Generated by gencpp from file swarm_exp_msgs/DtgFFEdge.msg
// DO NOT EDIT!


#ifndef SWARM_EXP_MSGS_MESSAGE_DTGFFEDGE_H
#define SWARM_EXP_MSGS_MESSAGE_DTGFFEDGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace swarm_exp_msgs
{
template <class ContainerAllocator>
struct DtgFFEdge_
{
  typedef DtgFFEdge_<ContainerAllocator> Type;

  DtgFFEdge_()
    : head_f_id(0)
    , tail_f_id(0)
    , points_idx()
    , head_v_id(0)
    , tail_v_id(0)
    , ffe_id(0)  {
    }
  DtgFFEdge_(const ContainerAllocator& _alloc)
    : head_f_id(0)
    , tail_f_id(0)
    , points_idx(_alloc)
    , head_v_id(0)
    , tail_v_id(0)
    , ffe_id(0)  {
  (void)_alloc;
    }



   typedef uint16_t _head_f_id_type;
  _head_f_id_type head_f_id;

   typedef uint16_t _tail_f_id_type;
  _tail_f_id_type tail_f_id;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _points_idx_type;
  _points_idx_type points_idx;

   typedef uint8_t _head_v_id_type;
  _head_v_id_type head_v_id;

   typedef uint8_t _tail_v_id_type;
  _tail_v_id_type tail_v_id;

   typedef uint8_t _ffe_id_type;
  _ffe_id_type ffe_id;





  typedef boost::shared_ptr< ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator> const> ConstPtr;

}; // struct DtgFFEdge_

typedef ::swarm_exp_msgs::DtgFFEdge_<std::allocator<void> > DtgFFEdge;

typedef boost::shared_ptr< ::swarm_exp_msgs::DtgFFEdge > DtgFFEdgePtr;
typedef boost::shared_ptr< ::swarm_exp_msgs::DtgFFEdge const> DtgFFEdgeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator2> & rhs)
{
  return lhs.head_f_id == rhs.head_f_id &&
    lhs.tail_f_id == rhs.tail_f_id &&
    lhs.points_idx == rhs.points_idx &&
    lhs.head_v_id == rhs.head_v_id &&
    lhs.tail_v_id == rhs.tail_v_id &&
    lhs.ffe_id == rhs.ffe_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_exp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "764ef8eb22d76355c9c291bdaa1ae595";
  }

  static const char* value(const ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x764ef8eb22d76355ULL;
  static const uint64_t static_value2 = 0xc9c291bdaa1ae595ULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_exp_msgs/DtgFFEdge";
  }

  static const char* value(const ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 head_f_id\n"
"uint16 tail_f_id\n"
"uint32[] points_idx #low res map\n"
"\n"
"uint8 head_v_id #viewpoint id of head fn\n"
"uint8 tail_v_id #viewpoint id of tail fn\n"
"uint8 ffe_id    #who creates\n"
;
  }

  static const char* value(const ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.head_f_id);
      stream.next(m.tail_f_id);
      stream.next(m.points_idx);
      stream.next(m.head_v_id);
      stream.next(m.tail_v_id);
      stream.next(m.ffe_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DtgFFEdge_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_exp_msgs::DtgFFEdge_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "head_f_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.head_f_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tail_f_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.tail_f_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "points_idx: ";
    if (v.points_idx.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.points_idx.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint32_t>::stream(s, true ? std::string() : indent + "    ", v.points_idx[i]);
    }
    if (v.points_idx.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "head_v_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.head_v_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tail_v_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tail_v_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ffe_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ffe_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_EXP_MSGS_MESSAGE_DTGFFEDGE_H
