// Generated by gencpp from file swarm_exp_msgs/DtgHNode.msg
// DO NOT EDIT!


#ifndef SWARM_EXP_MSGS_MESSAGE_DTGHNODE_H
#define SWARM_EXP_MSGS_MESSAGE_DTGHNODE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace swarm_exp_msgs
{
template <class ContainerAllocator>
struct DtgHNode_
{
  typedef DtgHNode_<ContainerAllocator> Type;

  DtgHNode_()
    : h_id(0)
    , pos_idx(0)  {
    }
  DtgHNode_(const ContainerAllocator& _alloc)
    : h_id(0)
    , pos_idx(0)  {
  (void)_alloc;
    }



   typedef uint32_t _h_id_type;
  _h_id_type h_id;

   typedef uint32_t _pos_idx_type;
  _pos_idx_type pos_idx;





  typedef boost::shared_ptr< ::swarm_exp_msgs::DtgHNode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_exp_msgs::DtgHNode_<ContainerAllocator> const> ConstPtr;

}; // struct DtgHNode_

typedef ::swarm_exp_msgs::DtgHNode_<std::allocator<void> > DtgHNode;

typedef boost::shared_ptr< ::swarm_exp_msgs::DtgHNode > DtgHNodePtr;
typedef boost::shared_ptr< ::swarm_exp_msgs::DtgHNode const> DtgHNodeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_exp_msgs::DtgHNode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_exp_msgs::DtgHNode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_exp_msgs::DtgHNode_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::DtgHNode_<ContainerAllocator2> & rhs)
{
  return lhs.h_id == rhs.h_id &&
    lhs.pos_idx == rhs.pos_idx;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_exp_msgs::DtgHNode_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::DtgHNode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_exp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::DtgHNode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::DtgHNode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::DtgHNode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::DtgHNode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::DtgHNode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::DtgHNode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_exp_msgs::DtgHNode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "61b258874ecfcb669e1516b9e9ebe709";
  }

  static const char* value(const ::swarm_exp_msgs::DtgHNode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x61b258874ecfcb66ULL;
  static const uint64_t static_value2 = 0x9e1516b9e9ebe709ULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_exp_msgs::DtgHNode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_exp_msgs/DtgHNode";
  }

  static const char* value(const ::swarm_exp_msgs::DtgHNode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_exp_msgs::DtgHNode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 h_id\n"
"uint32 pos_idx #low res map\n"
;
  }

  static const char* value(const ::swarm_exp_msgs::DtgHNode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_exp_msgs::DtgHNode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.h_id);
      stream.next(m.pos_idx);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DtgHNode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_exp_msgs::DtgHNode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_exp_msgs::DtgHNode_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "h_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.h_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pos_idx: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.pos_idx);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_EXP_MSGS_MESSAGE_DTGHNODE_H
