// Generated by gencpp from file swarm_exp_msgs/DtgHHEdge.msg
// DO NOT EDIT!


#ifndef SWARM_EXP_MSGS_MESSAGE_DTGHHEDGE_H
#define SWARM_EXP_MSGS_MESSAGE_DTGHHEDGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace swarm_exp_msgs
{
template <class ContainerAllocator>
struct DtgHHEdge_
{
  typedef DtgHHEdge_<ContainerAllocator> Type;

  DtgHHEdge_()
    : pub_t(0.0)
    , points_idx()
    , head_h_id(0)
    , tail_h_id(0)  {
    }
  DtgHHEdge_(const ContainerAllocator& _alloc)
    : pub_t(0.0)
    , points_idx(_alloc)
    , head_h_id(0)
    , tail_h_id(0)  {
  (void)_alloc;
    }



   typedef double _pub_t_type;
  _pub_t_type pub_t;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _points_idx_type;
  _points_idx_type points_idx;

   typedef uint32_t _head_h_id_type;
  _head_h_id_type head_h_id;

   typedef uint32_t _tail_h_id_type;
  _tail_h_id_type tail_h_id;





  typedef boost::shared_ptr< ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator> const> ConstPtr;

}; // struct DtgHHEdge_

typedef ::swarm_exp_msgs::DtgHHEdge_<std::allocator<void> > DtgHHEdge;

typedef boost::shared_ptr< ::swarm_exp_msgs::DtgHHEdge > DtgHHEdgePtr;
typedef boost::shared_ptr< ::swarm_exp_msgs::DtgHHEdge const> DtgHHEdgeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator2> & rhs)
{
  return lhs.pub_t == rhs.pub_t &&
    lhs.points_idx == rhs.points_idx &&
    lhs.head_h_id == rhs.head_h_id &&
    lhs.tail_h_id == rhs.tail_h_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_exp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f28c77b458771baddef5547b4e2a8c2d";
  }

  static const char* value(const ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf28c77b458771badULL;
  static const uint64_t static_value2 = 0xdef5547b4e2a8c2dULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_exp_msgs/DtgHHEdge";
  }

  static const char* value(const ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#uint8 hhe_id        #who creates\n"
"#bool erase \n"
"float64 pub_t\n"
"uint32[] points_idx #low res map\n"
"uint32 head_h_id\n"
"uint32 tail_h_id\n"
;
  }

  static const char* value(const ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pub_t);
      stream.next(m.points_idx);
      stream.next(m.head_h_id);
      stream.next(m.tail_h_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DtgHHEdge_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_exp_msgs::DtgHHEdge_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "pub_t: ";
    Printer<double>::stream(s, indent + "  ", v.pub_t);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "points_idx: ";
    if (v.points_idx.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.points_idx.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint32_t>::stream(s, true ? std::string() : indent + "    ", v.points_idx[i]);
    }
    if (v.points_idx.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "head_h_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.head_h_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tail_h_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.tail_h_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_EXP_MSGS_MESSAGE_DTGHHEDGE_H
