// Generated by gencpp from file swarm_exp_msgs/DtgHFEdge.msg
// DO NOT EDIT!


#ifndef SWARM_EXP_MSGS_MESSAGE_DTGHFEDGE_H
#define SWARM_EXP_MSGS_MESSAGE_DTGHFEDGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace swarm_exp_msgs
{
template <class ContainerAllocator>
struct DtgHFEdge_
{
  typedef DtgHFEdge_<ContainerAllocator> Type;

  DtgHFEdge_()
    : points_idx()
    , pub_t(0.0)
    , f_id(0)
    , h_id(0)
    , vp_id(0)  {
    }
  DtgHFEdge_(const ContainerAllocator& _alloc)
    : points_idx(_alloc)
    , pub_t(0.0)
    , f_id(0)
    , h_id(0)
    , vp_id(0)  {
  (void)_alloc;
    }



   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _points_idx_type;
  _points_idx_type points_idx;

   typedef double _pub_t_type;
  _pub_t_type pub_t;

   typedef uint16_t _f_id_type;
  _f_id_type f_id;

   typedef uint32_t _h_id_type;
  _h_id_type h_id;

   typedef uint8_t _vp_id_type;
  _vp_id_type vp_id;





  typedef boost::shared_ptr< ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator> const> ConstPtr;

}; // struct DtgHFEdge_

typedef ::swarm_exp_msgs::DtgHFEdge_<std::allocator<void> > DtgHFEdge;

typedef boost::shared_ptr< ::swarm_exp_msgs::DtgHFEdge > DtgHFEdgePtr;
typedef boost::shared_ptr< ::swarm_exp_msgs::DtgHFEdge const> DtgHFEdgeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator2> & rhs)
{
  return lhs.points_idx == rhs.points_idx &&
    lhs.pub_t == rhs.pub_t &&
    lhs.f_id == rhs.f_id &&
    lhs.h_id == rhs.h_id &&
    lhs.vp_id == rhs.vp_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_exp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9f0be3eb0a7ce0d70ee65a834e21ddf";
  }

  static const char* value(const ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9f0be3eb0a7ce0dULL;
  static const uint64_t static_value2 = 0x70ee65a834e21ddfULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_exp_msgs/DtgHFEdge";
  }

  static const char* value(const ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32[] points_idx #low res map\n"
"float64 pub_t\n"
"uint16 f_id\n"
"uint32 h_id\n"
"uint8 vp_id\n"
"#uint8 hfe_id        #who creates\n"
;
  }

  static const char* value(const ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points_idx);
      stream.next(m.pub_t);
      stream.next(m.f_id);
      stream.next(m.h_id);
      stream.next(m.vp_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DtgHFEdge_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_exp_msgs::DtgHFEdge_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "points_idx: ";
    if (v.points_idx.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.points_idx.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint32_t>::stream(s, true ? std::string() : indent + "    ", v.points_idx[i]);
    }
    if (v.points_idx.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pub_t: ";
    Printer<double>::stream(s, indent + "  ", v.pub_t);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "f_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.f_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "h_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.h_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vp_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.vp_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_EXP_MSGS_MESSAGE_DTGHFEDGE_H
