// Generated by gencpp from file swarm_exp_msgs/GroupState.msg
// DO NOT EDIT!


#ifndef SWARM_EXP_MSGS_MESSAGE_GROUPSTATE_H
#define SWARM_EXP_MSGS_MESSAGE_GROUPSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace swarm_exp_msgs
{
template <class ContainerAllocator>
struct GroupState_
{
  typedef GroupState_<ContainerAllocator> Type;

  GroupState_()
    : to_uavs()
    , from_uav(0)
    , cur_t(0.0)
    , group_size(0)
    , trooper_targets()
    , potential(0)
    , coverage_work_load(0)
    , state(0)  {
    }
  GroupState_(const ContainerAllocator& _alloc)
    : to_uavs(_alloc)
    , from_uav(0)
    , cur_t(0.0)
    , group_size(0)
    , trooper_targets(_alloc)
    , potential(0)
    , coverage_work_load(0)
    , state(0)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _to_uavs_type;
  _to_uavs_type to_uavs;

   typedef uint8_t _from_uav_type;
  _from_uav_type from_uav;

   typedef double _cur_t_type;
  _cur_t_type cur_t;

   typedef uint8_t _group_size_type;
  _group_size_type group_size;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _trooper_targets_type;
  _trooper_targets_type trooper_targets;

   typedef uint16_t _potential_type;
  _potential_type potential;

   typedef uint16_t _coverage_work_load_type;
  _coverage_work_load_type coverage_work_load;

   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::swarm_exp_msgs::GroupState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_exp_msgs::GroupState_<ContainerAllocator> const> ConstPtr;

}; // struct GroupState_

typedef ::swarm_exp_msgs::GroupState_<std::allocator<void> > GroupState;

typedef boost::shared_ptr< ::swarm_exp_msgs::GroupState > GroupStatePtr;
typedef boost::shared_ptr< ::swarm_exp_msgs::GroupState const> GroupStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_exp_msgs::GroupState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_exp_msgs::GroupState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_exp_msgs::GroupState_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::GroupState_<ContainerAllocator2> & rhs)
{
  return lhs.to_uavs == rhs.to_uavs &&
    lhs.from_uav == rhs.from_uav &&
    lhs.cur_t == rhs.cur_t &&
    lhs.group_size == rhs.group_size &&
    lhs.trooper_targets == rhs.trooper_targets &&
    lhs.potential == rhs.potential &&
    lhs.coverage_work_load == rhs.coverage_work_load &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_exp_msgs::GroupState_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::GroupState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_exp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::GroupState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::GroupState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::GroupState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::GroupState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::GroupState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::GroupState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_exp_msgs::GroupState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "17f63ea80422701593a5c33c707b7615";
  }

  static const char* value(const ::swarm_exp_msgs::GroupState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x17f63ea804227015ULL;
  static const uint64_t static_value2 = 0x93a5c33c707b7615ULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_exp_msgs::GroupState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_exp_msgs/GroupState";
  }

  static const char* value(const ::swarm_exp_msgs::GroupState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_exp_msgs::GroupState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# inter group broad cast (slow timer)\n"
"uint8[] to_uavs\n"
"uint8 from_uav\n"
"\n"
"float64 cur_t\n"
"uint8 group_size\n"
"uint32[] trooper_targets\n"
"uint16 potential #calculated unknown space number, for helpers\n"
"uint16 coverage_work_load\n"
"uint8 state # 0000 00(need help)(exp/cover)\n"
"\n"
;
  }

  static const char* value(const ::swarm_exp_msgs::GroupState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_exp_msgs::GroupState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.to_uavs);
      stream.next(m.from_uav);
      stream.next(m.cur_t);
      stream.next(m.group_size);
      stream.next(m.trooper_targets);
      stream.next(m.potential);
      stream.next(m.coverage_work_load);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GroupState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_exp_msgs::GroupState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_exp_msgs::GroupState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "to_uavs: ";
    if (v.to_uavs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.to_uavs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.to_uavs[i]);
    }
    if (v.to_uavs.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "from_uav: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.from_uav);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cur_t: ";
    Printer<double>::stream(s, indent + "  ", v.cur_t);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "group_size: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.group_size);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "trooper_targets: ";
    if (v.trooper_targets.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.trooper_targets.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint32_t>::stream(s, true ? std::string() : indent + "    ", v.trooper_targets[i]);
    }
    if (v.trooper_targets.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "potential: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.potential);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "coverage_work_load: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.coverage_work_load);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_EXP_MSGS_MESSAGE_GROUPSTATE_H
