// Generated by gencpp from file swarm_exp_msgs/GroupHelperRes.msg
// DO NOT EDIT!


#ifndef SWARM_EXP_MSGS_MESSAGE_GROUPHELPERRES_H
#define SWARM_EXP_MSGS_MESSAGE_GROUPHELPERRES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace swarm_exp_msgs
{
template <class ContainerAllocator>
struct GroupHelperRes_
{
  typedef GroupHelperRes_<ContainerAllocator> Type;

  GroupHelperRes_()
    : to_uavs()
    , from_uav(0)
    , allowed_num(0)  {
    }
  GroupHelperRes_(const ContainerAllocator& _alloc)
    : to_uavs(_alloc)
    , from_uav(0)
    , allowed_num(0)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _to_uavs_type;
  _to_uavs_type to_uavs;

   typedef uint8_t _from_uav_type;
  _from_uav_type from_uav;

   typedef uint8_t _allowed_num_type;
  _allowed_num_type allowed_num;





  typedef boost::shared_ptr< ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator> const> ConstPtr;

}; // struct GroupHelperRes_

typedef ::swarm_exp_msgs::GroupHelperRes_<std::allocator<void> > GroupHelperRes;

typedef boost::shared_ptr< ::swarm_exp_msgs::GroupHelperRes > GroupHelperResPtr;
typedef boost::shared_ptr< ::swarm_exp_msgs::GroupHelperRes const> GroupHelperResConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator2> & rhs)
{
  return lhs.to_uavs == rhs.to_uavs &&
    lhs.from_uav == rhs.from_uav &&
    lhs.allowed_num == rhs.allowed_num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_exp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1d5958dfe9e4c0dcd170ba5dda86e59";
  }

  static const char* value(const ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1d5958dfe9e4c0dULL;
  static const uint64_t static_value2 = 0xcd170ba5dda86e59ULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_exp_msgs/GroupHelperRes";
  }

  static const char* value(const ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# to certain group trooper (immediate answer)\n"
"uint8[] to_uavs\n"
"uint8 from_uav\n"
"\n"
"uint8 allowed_num\n"
;
  }

  static const char* value(const ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.to_uavs);
      stream.next(m.from_uav);
      stream.next(m.allowed_num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GroupHelperRes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_exp_msgs::GroupHelperRes_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "to_uavs: ";
    if (v.to_uavs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.to_uavs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.to_uavs[i]);
    }
    if (v.to_uavs.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "from_uav: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.from_uav);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "allowed_num: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.allowed_num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_EXP_MSGS_MESSAGE_GROUPHELPERRES_H
