// Generated by gencpp from file swarm_exp_msgs/GroupMap.msg
// DO NOT EDIT!


#ifndef SWARM_EXP_MSGS_MESSAGE_GROUPMAP_H
#define SWARM_EXP_MSGS_MESSAGE_GROUPMAP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace swarm_exp_msgs
{
template <class ContainerAllocator>
struct GroupMap_
{
  typedef GroupMap_<ContainerAllocator> Type;

  GroupMap_()
    {
    }
  GroupMap_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::swarm_exp_msgs::GroupMap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_exp_msgs::GroupMap_<ContainerAllocator> const> ConstPtr;

}; // struct GroupMap_

typedef ::swarm_exp_msgs::GroupMap_<std::allocator<void> > GroupMap;

typedef boost::shared_ptr< ::swarm_exp_msgs::GroupMap > GroupMapPtr;
typedef boost::shared_ptr< ::swarm_exp_msgs::GroupMap const> GroupMapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_exp_msgs::GroupMap_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_exp_msgs::GroupMap_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace swarm_exp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::GroupMap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::GroupMap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::GroupMap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::GroupMap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::GroupMap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::GroupMap_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_exp_msgs::GroupMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::swarm_exp_msgs::GroupMap_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_exp_msgs::GroupMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_exp_msgs/GroupMap";
  }

  static const char* value(const ::swarm_exp_msgs::GroupMap_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_exp_msgs::GroupMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# inside group broad cast (quick timer)\n"
;
  }

  static const char* value(const ::swarm_exp_msgs::GroupMap_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_exp_msgs::GroupMap_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GroupMap_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_exp_msgs::GroupMap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::swarm_exp_msgs::GroupMap_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_EXP_MSGS_MESSAGE_GROUPMAP_H
