// Generated by gencpp from file swarm_exp_msgs/GroupCommandReq.msg
// DO NOT EDIT!


#ifndef SWARM_EXP_MSGS_MESSAGE_GROUPCOMMANDREQ_H
#define SWARM_EXP_MSGS_MESSAGE_GROUPCOMMANDREQ_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace swarm_exp_msgs
{
template <class ContainerAllocator>
struct GroupCommandReq_
{
  typedef GroupCommandReq_<ContainerAllocator> Type;

  GroupCommandReq_()
    : to_uavs()
    , cur_t(0.0)
    , dispatch_type(0)
    , departure_EROIs()
    , departure_status(0)
    , helped_group_id(0)  {
    }
  GroupCommandReq_(const ContainerAllocator& _alloc)
    : to_uavs(_alloc)
    , cur_t(0.0)
    , dispatch_type(0)
    , departure_EROIs(_alloc)
    , departure_status(0)
    , helped_group_id(0)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _to_uavs_type;
  _to_uavs_type to_uavs;

   typedef double _cur_t_type;
  _cur_t_type cur_t;

   typedef uint8_t _dispatch_type_type;
  _dispatch_type_type dispatch_type;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _departure_EROIs_type;
  _departure_EROIs_type departure_EROIs;

   typedef uint8_t _departure_status_type;
  _departure_status_type departure_status;

   typedef uint8_t _helped_group_id_type;
  _helped_group_id_type helped_group_id;





  typedef boost::shared_ptr< ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator> const> ConstPtr;

}; // struct GroupCommandReq_

typedef ::swarm_exp_msgs::GroupCommandReq_<std::allocator<void> > GroupCommandReq;

typedef boost::shared_ptr< ::swarm_exp_msgs::GroupCommandReq > GroupCommandReqPtr;
typedef boost::shared_ptr< ::swarm_exp_msgs::GroupCommandReq const> GroupCommandReqConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator2> & rhs)
{
  return lhs.to_uavs == rhs.to_uavs &&
    lhs.cur_t == rhs.cur_t &&
    lhs.dispatch_type == rhs.dispatch_type &&
    lhs.departure_EROIs == rhs.departure_EROIs &&
    lhs.departure_status == rhs.departure_status &&
    lhs.helped_group_id == rhs.helped_group_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_exp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8907e16fca4b37e09a5750aaba75e3cc";
  }

  static const char* value(const ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8907e16fca4b37e0ULL;
  static const uint64_t static_value2 = 0x9a5750aaba75e3ccULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_exp_msgs/GroupCommandReq";
  }

  static const char* value(const ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# inside group, from trooper (Quick timmer)\n"
"uint8[] to_uavs\n"
"# uint8 from_uav\n"
"\n"
"float64 cur_t\n"
"# 1: Departure; 2: Help, 3: switch trooper\n"
"uint8 dispatch_type \n"
"\n"
"# departure\n"
"uint32[] departure_EROIs\n"
"uint8 departure_status #0: trooper; 1: infantry\n"
"\n"
"#help\n"
"uint8 helped_group_id\n"
"\n"
"\n"
;
  }

  static const char* value(const ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.to_uavs);
      stream.next(m.cur_t);
      stream.next(m.dispatch_type);
      stream.next(m.departure_EROIs);
      stream.next(m.departure_status);
      stream.next(m.helped_group_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GroupCommandReq_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_exp_msgs::GroupCommandReq_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "to_uavs: ";
    if (v.to_uavs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.to_uavs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.to_uavs[i]);
    }
    if (v.to_uavs.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cur_t: ";
    Printer<double>::stream(s, indent + "  ", v.cur_t);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dispatch_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dispatch_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "departure_EROIs: ";
    if (v.departure_EROIs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.departure_EROIs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint32_t>::stream(s, true ? std::string() : indent + "    ", v.departure_EROIs[i]);
    }
    if (v.departure_EROIs.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "departure_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.departure_status);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "helped_group_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.helped_group_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_EXP_MSGS_MESSAGE_GROUPCOMMANDREQ_H
