// Generated by gencpp from file swarm_exp_msgs/GroupHelperReq.msg
// DO NOT EDIT!


#ifndef SWARM_EXP_MSGS_MESSAGE_GROUPHELPERREQ_H
#define SWARM_EXP_MSGS_MESSAGE_GROUPHELPERREQ_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace swarm_exp_msgs
{
template <class ContainerAllocator>
struct GroupHelperReq_
{
  typedef GroupHelperReq_<ContainerAllocator> Type;

  GroupHelperReq_()
    : to_uavs()
    , from_uav(0)
    , helper_ids()
    , cost(0.0)  {
    }
  GroupHelperReq_(const ContainerAllocator& _alloc)
    : to_uavs(_alloc)
    , from_uav(0)
    , helper_ids(_alloc)
    , cost(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _to_uavs_type;
  _to_uavs_type to_uavs;

   typedef uint8_t _from_uav_type;
  _from_uav_type from_uav;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _helper_ids_type;
  _helper_ids_type helper_ids;

   typedef float _cost_type;
  _cost_type cost;





  typedef boost::shared_ptr< ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator> const> ConstPtr;

}; // struct GroupHelperReq_

typedef ::swarm_exp_msgs::GroupHelperReq_<std::allocator<void> > GroupHelperReq;

typedef boost::shared_ptr< ::swarm_exp_msgs::GroupHelperReq > GroupHelperReqPtr;
typedef boost::shared_ptr< ::swarm_exp_msgs::GroupHelperReq const> GroupHelperReqConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator2> & rhs)
{
  return lhs.to_uavs == rhs.to_uavs &&
    lhs.from_uav == rhs.from_uav &&
    lhs.helper_ids == rhs.helper_ids &&
    lhs.cost == rhs.cost;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_exp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de1dd505e44758dd2e830a3b48f4bffe";
  }

  static const char* value(const ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xde1dd505e44758ddULL;
  static const uint64_t static_value2 = 0x2e830a3b48f4bffeULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_exp_msgs/GroupHelperReq";
  }

  static const char* value(const ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# to certain group trooper (immediate answer)\n"
"uint8[] to_uavs\n"
"uint8 from_uav\n"
"\n"
"uint8[] helper_ids\n"
"float32 cost\n"
;
  }

  static const char* value(const ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.to_uavs);
      stream.next(m.from_uav);
      stream.next(m.helper_ids);
      stream.next(m.cost);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GroupHelperReq_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_exp_msgs::GroupHelperReq_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "to_uavs: ";
    if (v.to_uavs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.to_uavs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.to_uavs[i]);
    }
    if (v.to_uavs.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "from_uav: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.from_uav);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "helper_ids: ";
    if (v.helper_ids.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.helper_ids.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.helper_ids[i]);
    }
    if (v.helper_ids.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cost: ";
    Printer<float>::stream(s, indent + "  ", v.cost);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_EXP_MSGS_MESSAGE_GROUPHELPERREQ_H
