// Generated by gencpp from file swarm_exp_msgs/GroupMemberState.msg
// DO NOT EDIT!


#ifndef SWARM_EXP_MSGS_MESSAGE_GROUPMEMBERSTATE_H
#define SWARM_EXP_MSGS_MESSAGE_GROUPMEMBERSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace swarm_exp_msgs
{
template <class ContainerAllocator>
struct GroupMemberState_
{
  typedef GroupMemberState_<ContainerAllocator> Type;

  GroupMemberState_()
    : to_uavs()
    , from_uav(0)
    , cur_t(0.0)
    , targets()
    , work_type(0)  {
    }
  GroupMemberState_(const ContainerAllocator& _alloc)
    : to_uavs(_alloc)
    , from_uav(0)
    , cur_t(0.0)
    , targets(_alloc)
    , work_type(0)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _to_uavs_type;
  _to_uavs_type to_uavs;

   typedef uint8_t _from_uav_type;
  _from_uav_type from_uav;

   typedef double _cur_t_type;
  _cur_t_type cur_t;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _targets_type;
  _targets_type targets;

   typedef uint8_t _work_type_type;
  _work_type_type work_type;





  typedef boost::shared_ptr< ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator> const> ConstPtr;

}; // struct GroupMemberState_

typedef ::swarm_exp_msgs::GroupMemberState_<std::allocator<void> > GroupMemberState;

typedef boost::shared_ptr< ::swarm_exp_msgs::GroupMemberState > GroupMemberStatePtr;
typedef boost::shared_ptr< ::swarm_exp_msgs::GroupMemberState const> GroupMemberStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator2> & rhs)
{
  return lhs.to_uavs == rhs.to_uavs &&
    lhs.from_uav == rhs.from_uav &&
    lhs.cur_t == rhs.cur_t &&
    lhs.targets == rhs.targets &&
    lhs.work_type == rhs.work_type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_exp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abb6338d4d1acda965b2e312dd0c2bb4";
  }

  static const char* value(const ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xabb6338d4d1acda9ULL;
  static const uint64_t static_value2 = 0x65b2e312dd0c2bb4ULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_exp_msgs/GroupMemberState";
  }

  static const char* value(const ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# group broad cast (quick timer)\n"
"uint8[] to_uavs\n"
"uint8 from_uav\n"
"\n"
"float64 cur_t\n"
"uint32[] targets\n"
"uint8 work_type #cover, explore, follow, wait\n"
;
  }

  static const char* value(const ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.to_uavs);
      stream.next(m.from_uav);
      stream.next(m.cur_t);
      stream.next(m.targets);
      stream.next(m.work_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GroupMemberState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_exp_msgs::GroupMemberState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "to_uavs: ";
    if (v.to_uavs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.to_uavs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.to_uavs[i]);
    }
    if (v.to_uavs.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "from_uav: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.from_uav);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cur_t: ";
    Printer<double>::stream(s, indent + "  ", v.cur_t);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "targets: ";
    if (v.targets.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.targets.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint32_t>::stream(s, true ? std::string() : indent + "    ", v.targets[i]);
    }
    if (v.targets.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "work_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.work_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_EXP_MSGS_MESSAGE_GROUPMEMBERSTATE_H
