// Generated by gencpp from file swarm_exp_msgs/IdPose.msg
// DO NOT EDIT!


#ifndef SWARM_EXP_MSGS_MESSAGE_IDPOSE_H
#define SWARM_EXP_MSGS_MESSAGE_IDPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace swarm_exp_msgs
{
template <class ContainerAllocator>
struct IdPose_
{
  typedef IdPose_<ContainerAllocator> Type;

  IdPose_()
    : to_uavs()
    , id(0)
    , pub_t(0.0)
    , pose()  {
    }
  IdPose_(const ContainerAllocator& _alloc)
    : to_uavs(_alloc)
    , id(0)
    , pub_t(0.0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _to_uavs_type;
  _to_uavs_type to_uavs;

   typedef uint8_t _id_type;
  _id_type id;

   typedef double _pub_t_type;
  _pub_t_type pub_t;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::swarm_exp_msgs::IdPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_exp_msgs::IdPose_<ContainerAllocator> const> ConstPtr;

}; // struct IdPose_

typedef ::swarm_exp_msgs::IdPose_<std::allocator<void> > IdPose;

typedef boost::shared_ptr< ::swarm_exp_msgs::IdPose > IdPosePtr;
typedef boost::shared_ptr< ::swarm_exp_msgs::IdPose const> IdPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_exp_msgs::IdPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_exp_msgs::IdPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_exp_msgs::IdPose_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::IdPose_<ContainerAllocator2> & rhs)
{
  return lhs.to_uavs == rhs.to_uavs &&
    lhs.id == rhs.id &&
    lhs.pub_t == rhs.pub_t &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_exp_msgs::IdPose_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::IdPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_exp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::IdPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::IdPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::IdPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::IdPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::IdPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::IdPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_exp_msgs::IdPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc5f67458fe878e0f625ae446543e38e";
  }

  static const char* value(const ::swarm_exp_msgs::IdPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc5f67458fe878e0ULL;
  static const uint64_t static_value2 = 0xf625ae446543e38eULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_exp_msgs::IdPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_exp_msgs/IdPose";
  }

  static const char* value(const ::swarm_exp_msgs::IdPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_exp_msgs::IdPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# immediate for local or group, slow timer for general\n"
"uint8[] to_uavs\n"
"\n"
"uint8 id\n"
"float64 pub_t\n"
"geometry_msgs/Pose pose\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::swarm_exp_msgs::IdPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_exp_msgs::IdPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.to_uavs);
      stream.next(m.id);
      stream.next(m.pub_t);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IdPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_exp_msgs::IdPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_exp_msgs::IdPose_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "to_uavs: ";
    if (v.to_uavs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.to_uavs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.to_uavs[i]);
    }
    if (v.to_uavs.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pub_t: ";
    Printer<double>::stream(s, indent + "  ", v.pub_t);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_EXP_MSGS_MESSAGE_IDPOSE_H
