// Generated by gencpp from file swarm_exp_msgs/LocalTraj.msg
// DO NOT EDIT!


#ifndef SWARM_EXP_MSGS_MESSAGE_LOCALTRAJ_H
#define SWARM_EXP_MSGS_MESSAGE_LOCALTRAJ_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace swarm_exp_msgs
{
template <class ContainerAllocator>
struct LocalTraj_
{
  typedef LocalTraj_<ContainerAllocator> Type;

  LocalTraj_()
    : from_uav(0)
    , to_uavs()
    , state(0)
    , recover_pt()
    , start_t(0.0)
    , order_p(0)
    , t_p()
    , coef_p()
    , order_yaw(0)
    , t_yaw()
    , coef_yaw()  {
    }
  LocalTraj_(const ContainerAllocator& _alloc)
    : from_uav(0)
    , to_uavs(_alloc)
    , state(0)
    , recover_pt(_alloc)
    , start_t(0.0)
    , order_p(0)
    , t_p(_alloc)
    , coef_p(_alloc)
    , order_yaw(0)
    , t_yaw(_alloc)
    , coef_yaw(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _from_uav_type;
  _from_uav_type from_uav;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _to_uavs_type;
  _to_uavs_type to_uavs;

   typedef int8_t _state_type;
  _state_type state;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _recover_pt_type;
  _recover_pt_type recover_pt;

   typedef double _start_t_type;
  _start_t_type start_t;

   typedef int8_t _order_p_type;
  _order_p_type order_p;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _t_p_type;
  _t_p_type t_p;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _coef_p_type;
  _coef_p_type coef_p;

   typedef int8_t _order_yaw_type;
  _order_yaw_type order_yaw;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _t_yaw_type;
  _t_yaw_type t_yaw;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _coef_yaw_type;
  _coef_yaw_type coef_yaw;





  typedef boost::shared_ptr< ::swarm_exp_msgs::LocalTraj_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_exp_msgs::LocalTraj_<ContainerAllocator> const> ConstPtr;

}; // struct LocalTraj_

typedef ::swarm_exp_msgs::LocalTraj_<std::allocator<void> > LocalTraj;

typedef boost::shared_ptr< ::swarm_exp_msgs::LocalTraj > LocalTrajPtr;
typedef boost::shared_ptr< ::swarm_exp_msgs::LocalTraj const> LocalTrajConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_exp_msgs::LocalTraj_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_exp_msgs::LocalTraj_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_exp_msgs::LocalTraj_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::LocalTraj_<ContainerAllocator2> & rhs)
{
  return lhs.from_uav == rhs.from_uav &&
    lhs.to_uavs == rhs.to_uavs &&
    lhs.state == rhs.state &&
    lhs.recover_pt == rhs.recover_pt &&
    lhs.start_t == rhs.start_t &&
    lhs.order_p == rhs.order_p &&
    lhs.t_p == rhs.t_p &&
    lhs.coef_p == rhs.coef_p &&
    lhs.order_yaw == rhs.order_yaw &&
    lhs.t_yaw == rhs.t_yaw &&
    lhs.coef_yaw == rhs.coef_yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_exp_msgs::LocalTraj_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::LocalTraj_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_exp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::LocalTraj_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::LocalTraj_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::LocalTraj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::LocalTraj_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::LocalTraj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::LocalTraj_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_exp_msgs::LocalTraj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b2ad7fbcf01f3397172ee31bee3cc0b";
  }

  static const char* value(const ::swarm_exp_msgs::LocalTraj_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b2ad7fbcf01f339ULL;
  static const uint64_t static_value2 = 0x7172ee31bee3cc0bULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_exp_msgs::LocalTraj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_exp_msgs/LocalTraj";
  }

  static const char* value(const ::swarm_exp_msgs::LocalTraj_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_exp_msgs::LocalTraj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 from_uav\n"
"uint8[] to_uavs\n"
"\n"
"int8 state\n"
"\n"
"geometry_msgs/Point recover_pt\n"
"\n"
"float64 start_t\n"
"int8 order_p\n"
"float32[] t_p\n"
"geometry_msgs/Point[] coef_p\n"
"\n"
"int8 order_yaw\n"
"float32[] t_yaw\n"
"float32[] coef_yaw\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::swarm_exp_msgs::LocalTraj_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_exp_msgs::LocalTraj_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.from_uav);
      stream.next(m.to_uavs);
      stream.next(m.state);
      stream.next(m.recover_pt);
      stream.next(m.start_t);
      stream.next(m.order_p);
      stream.next(m.t_p);
      stream.next(m.coef_p);
      stream.next(m.order_yaw);
      stream.next(m.t_yaw);
      stream.next(m.coef_yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocalTraj_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_exp_msgs::LocalTraj_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_exp_msgs::LocalTraj_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "from_uav: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.from_uav);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "to_uavs: ";
    if (v.to_uavs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.to_uavs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.to_uavs[i]);
    }
    if (v.to_uavs.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "recover_pt: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.recover_pt);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "start_t: ";
    Printer<double>::stream(s, indent + "  ", v.start_t);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "order_p: ";
    Printer<int8_t>::stream(s, indent + "  ", v.order_p);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "t_p: ";
    if (v.t_p.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.t_p.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.t_p[i]);
    }
    if (v.t_p.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "coef_p: ";
    if (v.coef_p.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.coef_p.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.coef_p[i]);
    }
    if (v.coef_p.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "order_yaw: ";
    Printer<int8_t>::stream(s, indent + "  ", v.order_yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "t_yaw: ";
    if (v.t_yaw.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.t_yaw.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.t_yaw[i]);
    }
    if (v.t_yaw.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "coef_yaw: ";
    if (v.coef_yaw.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.coef_yaw.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.coef_yaw[i]);
    }
    if (v.coef_yaw.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_EXP_MSGS_MESSAGE_LOCALTRAJ_H
