// Generated by gencpp from file swarm_exp_msgs/SwarmTraj.msg
// DO NOT EDIT!


#ifndef SWARM_EXP_MSGS_MESSAGE_SWARMTRAJ_H
#define SWARM_EXP_MSGS_MESSAGE_SWARMTRAJ_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace swarm_exp_msgs
{
template <class ContainerAllocator>
struct SwarmTraj_
{
  typedef SwarmTraj_<ContainerAllocator> Type;

  SwarmTraj_()
    : to_uavs()
    , from_uav(0)
    , start_t(0.0)
    , order_p(0)
    , t_p()
    , coef_p()  {
    }
  SwarmTraj_(const ContainerAllocator& _alloc)
    : to_uavs(_alloc)
    , from_uav(0)
    , start_t(0.0)
    , order_p(0)
    , t_p(_alloc)
    , coef_p(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _to_uavs_type;
  _to_uavs_type to_uavs;

   typedef uint8_t _from_uav_type;
  _from_uav_type from_uav;

   typedef double _start_t_type;
  _start_t_type start_t;

   typedef int8_t _order_p_type;
  _order_p_type order_p;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _t_p_type;
  _t_p_type t_p;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _coef_p_type;
  _coef_p_type coef_p;





  typedef boost::shared_ptr< ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator> const> ConstPtr;

}; // struct SwarmTraj_

typedef ::swarm_exp_msgs::SwarmTraj_<std::allocator<void> > SwarmTraj;

typedef boost::shared_ptr< ::swarm_exp_msgs::SwarmTraj > SwarmTrajPtr;
typedef boost::shared_ptr< ::swarm_exp_msgs::SwarmTraj const> SwarmTrajConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator2> & rhs)
{
  return lhs.to_uavs == rhs.to_uavs &&
    lhs.from_uav == rhs.from_uav &&
    lhs.start_t == rhs.start_t &&
    lhs.order_p == rhs.order_p &&
    lhs.t_p == rhs.t_p &&
    lhs.coef_p == rhs.coef_p;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator1> & lhs, const ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_exp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad6c481b3a1cd3eae78b78f76fc6821d";
  }

  static const char* value(const ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad6c481b3a1cd3eaULL;
  static const uint64_t static_value2 = 0xe78b78f76fc6821dULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_exp_msgs/SwarmTraj";
  }

  static const char* value(const ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# immediate for local or group\n"
"\n"
"uint8[] to_uavs\n"
"uint8 from_uav\n"
"\n"
"float64 start_t\n"
"int8 order_p\n"
"float32[] t_p\n"
"geometry_msgs/Point[] coef_p\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.to_uavs);
      stream.next(m.from_uav);
      stream.next(m.start_t);
      stream.next(m.order_p);
      stream.next(m.t_p);
      stream.next(m.coef_p);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SwarmTraj_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_exp_msgs::SwarmTraj_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "to_uavs: ";
    if (v.to_uavs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.to_uavs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.to_uavs[i]);
    }
    if (v.to_uavs.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "from_uav: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.from_uav);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "start_t: ";
    Printer<double>::stream(s, indent + "  ", v.start_t);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "order_p: ";
    Printer<int8_t>::stream(s, indent + "  ", v.order_p);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "t_p: ";
    if (v.t_p.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.t_p.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.t_p[i]);
    }
    if (v.t_p.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "coef_p: ";
    if (v.coef_p.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.coef_p.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.coef_p[i]);
    }
    if (v.coef_p.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_EXP_MSGS_MESSAGE_SWARMTRAJ_H
