set(_CATKIN_CURRENT_PACKAGE "mr_dtg_plus")
set(mr_dtg_plus_VERSION "0.0.0")
set(mr_dtg_plus_MAINTAINER "CharlieDog <qianlidong@mail.nankai.edu.cn>")
set(mr_dtg_plus_PACKAGE_FORMAT "2")
set(mr_dtg_plus_BUILD_DEPENDS "roscpp" "visualization_msgs" "sensor_msgs" "geometry_msgs" "block_map_lite" "lowres_map_lite" "eroi" "swarm_data")
set(mr_dtg_plus_BUILD_EXPORT_DEPENDS "roscpp" "visualization_msgs" "sensor_msgs" "geometry_msgs" "block_map_lite" "lowres_map_lite" "eroi" "swarm_data")
set(mr_dtg_plus_BUILDTOOL_DEPENDS "catkin" "catkin_simple")
set(mr_dtg_plus_BUILDTOOL_EXPORT_DEPENDS )
set(mr_dtg_plus_EXEC_DEPENDS "roscpp" "visualization_msgs" "sensor_msgs" "geometry_msgs" "block_map_lite" "lowres_map_lite" "eroi" "swarm_data")
set(mr_dtg_plus_RUN_DEPENDS "roscpp" "visualization_msgs" "sensor_msgs" "geometry_msgs" "block_map_lite" "lowres_map_lite" "eroi" "swarm_data")
set(mr_dtg_plus_TEST_DEPENDS )
set(mr_dtg_plus_DOC_DEPENDS )
set(mr_dtg_plus_URL_WEBSITE "")
set(mr_dtg_plus_URL_BUGTRACKER "")
set(mr_dtg_plus_URL_REPOSITORY "")
set(mr_dtg_plus_DEPRECATED "")