set(_CATKIN_CURRENT_PACKAGE "eden")
set(eden_VERSION "0.0.0")
set(eden_MAINTAINER "CharlieDog <qianlidong@mail.nankai.edu.cn>")
set(eden_PACKAGE_FORMAT "2")
set(eden_BUILD_DEPENDS "mr_dtg_plus" "block_map_lite" "lowres_map_lite" "geometry_msgs" "trajectory_msgs" "gflags_catkin" "visualization_msgs" "glog_catkin" "gcopter" "eroi")
set(eden_BUILD_EXPORT_DEPENDS "mr_dtg_plus" "block_map_lite" "lowres_map_lite" "geometry_msgs" "trajectory_msgs" "gflags_catkin" "visualization_msgs" "glog_catkin" "gcopter" "eroi")
set(eden_BUILDTOOL_DEPENDS "catkin" "catkin_simple")
set(eden_BUILDTOOL_EXPORT_DEPENDS )
set(eden_EXEC_DEPENDS "mr_dtg_plus" "block_map_lite" "lowres_map_lite" "geometry_msgs" "trajectory_msgs" "gflags_catkin" "visualization_msgs" "glog_catkin" "gcopter" "eroi")
set(eden_RUN_DEPENDS "mr_dtg_plus" "block_map_lite" "lowres_map_lite" "geometry_msgs" "trajectory_msgs" "gflags_catkin" "visualization_msgs" "glog_catkin" "gcopter" "eroi")
set(eden_TEST_DEPENDS )
set(eden_DOC_DEPENDS )
set(eden_URL_WEBSITE "")
set(eden_URL_BUGTRACKER "")
set(eden_URL_REPOSITORY "")
set(eden_DEPRECATED "")